/**
 * Policy Pack Service
 * Main orchestration service for policy generation
 */
import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '@libs/database';
import { PolicyGeneratorService } from './services/policy-generator.service';
import { ControlMappingService } from './services/control-mapping.service';
import { OpaPolicyService } from './services/opa-policy.service';
import { TerraformRulesService } from './services/terraform-rules.service';
import { PolicyExportService } from './services/policy-export.service';
import { PolicyPackBundle, PolicyDocument, OpaPolicy } from './types';
import { GapContext } from '../qpg/types';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
export class PolicyPackService {
  private readonly logger = new Logger(PolicyPackService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly policyGenerator: PolicyGeneratorService,
    private readonly controlMapping: ControlMappingService,
    private readonly opaPolicy: OpaPolicyService,
    private readonly terraformRules: TerraformRulesService,
    private readonly exportService: PolicyExportService,
  ) {}

  /**
   * Generate complete policy pack from session gaps
   */
  async generatePolicyPack(sessionId: string, gaps: GapContext[]): Promise<PolicyPackBundle> {
    this.logger.log(`Generating policy pack for session: ${sessionId}`);

    // Generate policies for each gap
    const policies: PolicyDocument[] = [];
    const dimensionsCovered = new Set<string>();

    for (const gap of gaps) {
      try {
        const policy = await this.policyGenerator.generatePolicyForGap(gap);
        policies.push(policy);
        dimensionsCovered.add(gap.dimensionKey);
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        this.logger.warn(`Failed to generate policy for gap ${gap.questionId}: ${errorMessage}`);
      }
    }

    // Get OPA policies for covered dimensions
    const opaPolicies: OpaPolicy[] = [];
    for (const dimension of dimensionsCovered) {
      const dimensionPolicies = this.opaPolicy.getPoliciesForDimension(dimension);
      opaPolicies.push(...dimensionPolicies);
    }

    // Get Terraform rules for covered dimensions
    const terraformRulesArr = [];
    for (const dimension of dimensionsCovered) {
      const rules = this.terraformRules.getRulesForDimension(dimension);
      terraformRulesArr.push(...rules);
    }
    const terraformRulesContent = this.terraformRules.generateFeatureFile(terraformRulesArr);

    // Get score at generation
    const session = await this.prisma.session.findUnique({
      where: { id: sessionId },
    });
    const scoreAtGeneration = session?.readinessScore
      ? typeof session.readinessScore === 'number'
        ? session.readinessScore
        : ((session.readinessScore as any).toNumber?.() ?? Number(session.readinessScore))
      : 0;

    const bundle: PolicyPackBundle = {
      id: `pack-${uuidv4()}`,
      name: `Quiz2Biz Policy Pack - ${new Date().toISOString().split('T')[0]}`,
      version: '1.0.0',
      generatedAt: new Date(),
      policies,
      opaPolicies,
      terraformRules: terraformRulesContent,
      readmeContent: '', // Will be generated by export service
      sourceSessionId: sessionId,
      scoreAtGeneration,
    };

    // Generate README
    bundle.readmeContent = this.exportService.generateReadme(bundle);

    this.logger.log(
      `Generated policy pack with ${policies.length} policies, ${opaPolicies.length} OPA policies`,
    );

    return bundle;
  }

  /**
   * Get export structure for download
   */
  getExportStructure(bundle: PolicyPackBundle) {
    return this.exportService.getExportStructure(bundle);
  }

  /**
   * Get control mappings for a dimension
   */
  getControlMappings(dimensionKey: string) {
    return this.controlMapping.getMappingsForDimension(dimensionKey);
  }

  /**
   * Get all OPA policies
   */
  getAllOpaPolicies() {
    return this.opaPolicy.getAllPolicies();
  }

  /**
   * Get all Terraform rules
   */
  getAllTerraformRules() {
    return this.terraformRules.getAllRules();
  }

  /**
   * Generate combined OPA policy file
   */
  generateCombinedOpaFile(policies: OpaPolicy[]) {
    return this.opaPolicy.generateCombinedRegoFile(policies);
  }
}
