import { QuestionType, Persona } from '@prisma/client';

/**
 * BA Questions - 35+ questions for Requirements, UX, Policy-to-Control Mapping
 *
 * Categories:
 * - Requirements Engineering (12 questions)
 * - User Experience & Design (12 questions)
 * - Policy-to-Control Mapping (11 questions)
 */

export interface BAQuestion {
  id: string;
  text: string;
  type: QuestionType;
  persona: Persona;
  dimensionKey: string;
  severity: number;
  bestPractice: string;
  practicalExplainer: string;
  standardRefs: string;
  acceptance: string;
  helpText?: string;
  options?: { id: string; label: string; value: string }[];
  isRequired?: boolean;
  orderIndex: number;
}

// ==========================================
// REQUIREMENTS ENGINEERING (12)
// ==========================================
export const requirementsQuestions: BAQuestion[] = [
  {
    id: 'q-ba-001',
    text: 'Do you have a formal requirements elicitation process?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.8,
    bestPractice: 'Use structured techniques: interviews, workshops, prototyping, observation',
    practicalExplainer: 'Formal elicitation ensures requirements capture real user needs.',
    standardRefs: 'IIBA BABOK, IEEE 830, ISO 29148',
    acceptance: 'Elicitation techniques documented; stakeholders identified; sessions scheduled',
    orderIndex: 3,
    options: [
      { id: 'ba-001-1', label: 'Yes, structured elicitation process', value: 'full' },
      { id: 'ba-001-2', label: 'Some techniques used', value: 'partial' },
      { id: 'ba-001-3', label: 'Ad-hoc requirements gathering', value: 'minimal' },
      { id: 'ba-001-4', label: 'No formal process', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-002',
    text: 'Are requirements prioritized using a consistent framework?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.77,
    bestPractice: 'Use MoSCoW, RICE, or weighted scoring; involve stakeholders',
    practicalExplainer: 'Prioritization ensures the most valuable features are built first.',
    standardRefs: 'MoSCoW Method, RICE Framework, Weighted Shortest Job First',
    acceptance: 'Prioritization framework documented; backlog prioritized; stakeholder buy-in',
    orderIndex: 4,
    options: [
      { id: 'ba-002-1', label: 'Yes, consistent prioritization framework', value: 'full' },
      { id: 'ba-002-2', label: 'Basic prioritization used', value: 'partial' },
      { id: 'ba-002-3', label: 'Informal prioritization', value: 'minimal' },
      { id: 'ba-002-4', label: 'No prioritization framework', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-003',
    text: 'Do you document non-functional requirements (NFRs)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.82,
    bestPractice: 'Define NFRs for performance, security, scalability, availability',
    practicalExplainer: 'NFRs define how the system should behave, not just what it does.',
    standardRefs: 'ISO 25010, FURPS+, BABOK NFR Categories',
    acceptance: 'NFRs documented; measurable criteria defined; tested in acceptance',
    orderIndex: 5,
    options: [
      { id: 'ba-003-1', label: 'Yes, comprehensive NFR documentation', value: 'full' },
      { id: 'ba-003-2', label: 'Some NFRs documented', value: 'partial' },
      { id: 'ba-003-3', label: 'Informal NFR awareness', value: 'minimal' },
      { id: 'ba-003-4', label: 'No NFR documentation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-004',
    text: 'Do you maintain a product backlog with groomed items?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.79,
    bestPractice: 'Maintain prioritized backlog; groom 2-3 sprints ahead; definition of ready',
    practicalExplainer: 'A groomed backlog ensures development can start immediately.',
    standardRefs: 'Scrum Guide, SAFe Product Management, Kanban',
    acceptance: 'Backlog exists; items meet DoR; regular grooming sessions',
    orderIndex: 6,
    options: [
      { id: 'ba-004-1', label: 'Yes, well-maintained backlog', value: 'full' },
      { id: 'ba-004-2', label: 'Backlog exists, needs grooming', value: 'partial' },
      { id: 'ba-004-3', label: 'Basic list of features', value: 'minimal' },
      { id: 'ba-004-4', label: 'No product backlog', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-005',
    text: 'Do you have a change management process for requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.75,
    bestPractice: 'Implement change control board; impact analysis; version control',
    practicalExplainer: 'Change management prevents scope creep and uncontrolled changes.',
    standardRefs: 'BABOK Change Management, ITIL Change Management, PMI',
    acceptance: 'Change process documented; impact analysis required; approval workflow',
    orderIndex: 7,
    options: [
      { id: 'ba-005-1', label: 'Yes, formal change management', value: 'full' },
      { id: 'ba-005-2', label: 'Basic change tracking', value: 'partial' },
      { id: 'ba-005-3', label: 'Informal change handling', value: 'minimal' },
      { id: 'ba-005-4', label: 'No change management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-006',
    text: 'Do you use acceptance criteria and definition of done?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.81,
    bestPractice: 'Every story has acceptance criteria; team-wide definition of done',
    practicalExplainer: 'Clear criteria ensure everyone agrees when work is complete.',
    standardRefs: 'Scrum Guide DoD, BDD Given-When-Then, INVEST Stories',
    acceptance: 'All stories have AC; DoD defined; consistently applied',
    orderIndex: 8,
    options: [
      { id: 'ba-006-1', label: 'Yes, AC and DoD consistently used', value: 'full' },
      { id: 'ba-006-2', label: 'AC on most stories', value: 'partial' },
      { id: 'ba-006-3', label: 'Some acceptance criteria', value: 'minimal' },
      { id: 'ba-006-4', label: 'No AC or DoD', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-007',
    text: 'Do you create user journey maps for key workflows?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.73,
    bestPractice: 'Map end-to-end user journeys; identify pain points and opportunities',
    practicalExplainer: 'Journey maps reveal the complete user experience across touchpoints.',
    standardRefs: 'UX Design, Service Design, Customer Journey Mapping',
    acceptance: 'Key journeys mapped; pain points identified; improvements prioritized',
    orderIndex: 9,
    options: [
      { id: 'ba-007-1', label: 'Yes, comprehensive journey maps', value: 'full' },
      { id: 'ba-007-2', label: 'Some key journeys mapped', value: 'partial' },
      { id: 'ba-007-3', label: 'High-level flow diagrams', value: 'minimal' },
      { id: 'ba-007-4', label: 'No journey mapping', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-008',
    text: 'Do you have a glossary of business terms?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.68,
    bestPractice: 'Maintain ubiquitous language glossary; align business and technical terms',
    practicalExplainer: 'A glossary ensures everyone uses the same terminology.',
    standardRefs: 'DDD Ubiquitous Language, BABOK Glossary, Data Dictionary',
    acceptance: 'Glossary exists; key terms defined; used in requirements',
    orderIndex: 10,
    options: [
      { id: 'ba-008-1', label: 'Yes, maintained glossary', value: 'full' },
      { id: 'ba-008-2', label: 'Basic term definitions', value: 'partial' },
      { id: 'ba-008-3', label: 'Informal understanding', value: 'minimal' },
      { id: 'ba-008-4', label: 'No glossary', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-009',
    text: 'Do you conduct requirements reviews with stakeholders?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.76,
    bestPractice: 'Schedule regular reviews; document sign-off; track changes',
    practicalExplainer: 'Reviews ensure requirements accurately reflect stakeholder needs.',
    standardRefs: 'BABOK Requirements Validation, IEEE 1028, Inspection Process',
    acceptance: 'Reviews scheduled; stakeholder sign-off obtained; feedback incorporated',
    orderIndex: 11,
    options: [
      { id: 'ba-009-1', label: 'Yes, regular stakeholder reviews', value: 'full' },
      { id: 'ba-009-2', label: 'Occasional reviews', value: 'partial' },
      { id: 'ba-009-3', label: 'Informal feedback', value: 'minimal' },
      { id: 'ba-009-4', label: 'No requirement reviews', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-010',
    text: 'Do you document business rules separately from requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.72,
    bestPractice: 'Catalog business rules; link to requirements; test for compliance',
    practicalExplainer: 'Separating business rules makes them reusable and maintainable.',
    standardRefs: 'BABOK Business Rules, Decision Tables, SBVR',
    acceptance: 'Business rules documented; linked to requirements; test coverage',
    orderIndex: 12,
    options: [
      { id: 'ba-010-1', label: 'Yes, business rules cataloged', value: 'full' },
      { id: 'ba-010-2', label: 'Some rules documented', value: 'partial' },
      { id: 'ba-010-3', label: 'Rules embedded in requirements', value: 'minimal' },
      { id: 'ba-010-4', label: 'No business rules documentation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-011',
    text: 'Do you create process models (BPMN/flowcharts)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.74,
    bestPractice: 'Model key processes in BPMN; identify automation opportunities',
    practicalExplainer: 'Process models visualize workflows and help identify improvements.',
    standardRefs: 'BPMN 2.0, UML Activity Diagrams, Lean Process Mapping',
    acceptance: 'Key processes modeled; stakeholder validated; automation identified',
    orderIndex: 13,
    options: [
      { id: 'ba-011-1', label: 'Yes, BPMN process models', value: 'full' },
      { id: 'ba-011-2', label: 'Basic flowcharts', value: 'partial' },
      { id: 'ba-011-3', label: 'Informal process descriptions', value: 'minimal' },
      { id: 'ba-011-4', label: 'No process modeling', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-012',
    text: 'Do you estimate requirements complexity and effort?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.71,
    bestPractice: 'Use story points or t-shirt sizing; track velocity; refine estimates',
    practicalExplainer: 'Estimation helps plan releases and manage expectations.',
    standardRefs: 'Scrum Estimation, Planning Poker, Affinity Estimation',
    acceptance: 'Estimation process defined; backlog estimated; velocity tracked',
    orderIndex: 14,
    options: [
      { id: 'ba-012-1', label: 'Yes, consistent estimation process', value: 'full' },
      { id: 'ba-012-2', label: 'Basic estimation', value: 'partial' },
      { id: 'ba-012-3', label: 'Ad-hoc estimates', value: 'minimal' },
      { id: 'ba-012-4', label: 'No estimation', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// USER EXPERIENCE & DESIGN (12)
// ==========================================
export const uxDesignQuestions: BAQuestion[] = [
  {
    id: 'q-ba-013',
    text: 'Do you conduct user research before designing features?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.79,
    bestPractice: 'Conduct user interviews, surveys, and observation before design',
    practicalExplainer: 'User research ensures you build what users actually need.',
    standardRefs: 'UX Research Methods, IDEO Human-Centered Design, NNG',
    acceptance: 'Research conducted; insights documented; design informed by findings',
    orderIndex: 15,
    options: [
      { id: 'ba-013-1', label: 'Yes, regular user research', value: 'full' },
      { id: 'ba-013-2', label: 'Occasional user research', value: 'partial' },
      { id: 'ba-013-3', label: 'Informal user feedback', value: 'minimal' },
      { id: 'ba-013-4', label: 'No user research', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-014',
    text: 'Do you create wireframes/prototypes before development?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.76,
    bestPractice: 'Create low-fi wireframes; iterate to high-fi prototypes; user test',
    practicalExplainer: 'Prototypes validate designs before expensive development.',
    standardRefs: 'Design Thinking, Figma/Sketch, InVision, Adobe XD',
    acceptance: 'Wireframes created; stakeholder approved; user tested before dev',
    orderIndex: 16,
    options: [
      { id: 'ba-014-1', label: 'Yes, wireframes and prototypes', value: 'full' },
      { id: 'ba-014-2', label: 'Wireframes for key features', value: 'partial' },
      { id: 'ba-014-3', label: 'Basic sketches', value: 'minimal' },
      { id: 'ba-014-4', label: 'No prototyping', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-015',
    text: 'Do you have a design system or style guide?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.74,
    bestPractice: 'Create design system with components, patterns, and guidelines',
    practicalExplainer: 'Design systems ensure consistency and speed up development.',
    standardRefs: 'Atomic Design, Material Design, Carbon Design System',
    acceptance: 'Design system exists; components documented; consistently used',
    orderIndex: 17,
    options: [
      { id: 'ba-015-1', label: 'Yes, comprehensive design system', value: 'full' },
      { id: 'ba-015-2', label: 'Basic style guide', value: 'partial' },
      { id: 'ba-015-3', label: 'Informal design conventions', value: 'minimal' },
      { id: 'ba-015-4', label: 'No design system', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-016',
    text: 'Do you conduct usability testing with real users?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'quality_test',
    severity: 0.77,
    bestPractice: 'Test with 5+ users per round; iterate based on findings; test early and often',
    practicalExplainer: 'Usability testing reveals problems before they reach production.',
    standardRefs: 'NNG Usability Testing, Rocket Surgery Made Easy, Think Aloud Protocol',
    acceptance: 'Regular usability testing; findings documented; designs improved',
    orderIndex: 6,
    options: [
      { id: 'ba-016-1', label: 'Yes, regular usability testing', value: 'full' },
      { id: 'ba-016-2', label: 'Occasional testing', value: 'partial' },
      { id: 'ba-016-3', label: 'Internal testing only', value: 'minimal' },
      { id: 'ba-016-4', label: 'No usability testing', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-017',
    text: 'Do you have documented user personas?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.72,
    bestPractice: 'Create research-based personas; use for design decisions',
    practicalExplainer: 'Personas help the team empathize with target users.',
    standardRefs: 'Alan Cooper Personas, UX Personas, Jobs-to-be-Done',
    acceptance: 'Personas documented; research-based; used in design decisions',
    orderIndex: 18,
    options: [
      { id: 'ba-017-1', label: 'Yes, research-based personas', value: 'full' },
      { id: 'ba-017-2', label: 'Basic persona descriptions', value: 'partial' },
      { id: 'ba-017-3', label: 'Informal user understanding', value: 'minimal' },
      { id: 'ba-017-4', label: 'No personas', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-018',
    text: 'Do you measure and optimize user experience metrics?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'quality_test',
    severity: 0.75,
    bestPractice: 'Track NPS, CSAT, SUS, task completion rate; optimize continuously',
    practicalExplainer: 'UX metrics quantify the user experience for improvement.',
    standardRefs: 'System Usability Scale, Net Promoter Score, HEART Framework',
    acceptance: 'UX metrics defined; tracked regularly; targets set',
    orderIndex: 7,
    options: [
      { id: 'ba-018-1', label: 'Yes, UX metrics tracked', value: 'full' },
      { id: 'ba-018-2', label: 'Basic satisfaction surveys', value: 'partial' },
      { id: 'ba-018-3', label: 'Informal feedback', value: 'minimal' },
      { id: 'ba-018-4', label: 'No UX metrics', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-019',
    text: 'Do you have responsive/mobile-first design approach?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.78,
    bestPractice: 'Design mobile-first; test on multiple devices and screen sizes',
    practicalExplainer: 'Mobile-first ensures your app works well on all devices.',
    standardRefs: 'Responsive Web Design, Mobile-First Strategy, Progressive Enhancement',
    acceptance: 'Mobile-first approach documented; tested on multiple devices',
    orderIndex: 19,
    options: [
      { id: 'ba-019-1', label: 'Yes, mobile-first design', value: 'full' },
      { id: 'ba-019-2', label: 'Responsive design', value: 'partial' },
      { id: 'ba-019-3', label: 'Desktop-focused with mobile support', value: 'minimal' },
      { id: 'ba-019-4', label: 'Desktop only', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-020',
    text: 'Do you design for error prevention and recovery?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.73,
    bestPractice: 'Design to prevent errors; provide clear error messages and recovery paths',
    practicalExplainer: 'Good error handling reduces frustration and support requests.',
    standardRefs: 'Nielsen Heuristics #5 #9, Error Prevention, Defensive Design',
    acceptance: 'Error scenarios mapped; prevention designed; clear error messages',
    orderIndex: 20,
    options: [
      { id: 'ba-020-1', label: 'Yes, comprehensive error design', value: 'full' },
      { id: 'ba-020-2', label: 'Basic error handling', value: 'partial' },
      { id: 'ba-020-3', label: 'Some error messages', value: 'minimal' },
      { id: 'ba-020-4', label: 'No error design', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-021',
    text: 'Do you follow UX heuristics in your designs?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.74,
    bestPractice: 'Apply Nielsen 10 heuristics; conduct heuristic evaluations',
    practicalExplainer: 'UX heuristics are proven principles for good user interfaces.',
    standardRefs: 'Nielsen 10 Usability Heuristics, Shneiderman Golden Rules',
    acceptance: 'Heuristics documented; evaluations conducted; findings addressed',
    orderIndex: 21,
    options: [
      { id: 'ba-021-1', label: 'Yes, heuristics applied consistently', value: 'full' },
      { id: 'ba-021-2', label: 'Some heuristics considered', value: 'partial' },
      { id: 'ba-021-3', label: 'Informal UX awareness', value: 'minimal' },
      { id: 'ba-021-4', label: 'No UX heuristics used', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-022',
    text: 'Do you have onboarding flow designed for new users?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.71,
    bestPractice: 'Design guided onboarding; measure time-to-value; optimize activation',
    practicalExplainer: 'Good onboarding helps users get value quickly and stay.',
    standardRefs: 'Samuel Hulick Onboarding, Product-Led Growth, Activation',
    acceptance: 'Onboarding designed; time-to-value measured; activation tracked',
    orderIndex: 22,
    options: [
      { id: 'ba-022-1', label: 'Yes, optimized onboarding flow', value: 'full' },
      { id: 'ba-022-2', label: 'Basic onboarding', value: 'partial' },
      { id: 'ba-022-3', label: 'Minimal guidance', value: 'minimal' },
      { id: 'ba-022-4', label: 'No onboarding design', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-023',
    text: 'Do you track and analyze user behavior analytics?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'data_ai',
    severity: 0.76,
    bestPractice: 'Track user actions; analyze funnels; use insights for optimization',
    practicalExplainer: 'Analytics reveal how users actually interact with your product.',
    standardRefs: 'Mixpanel, Amplitude, Google Analytics, Heap',
    acceptance: 'Analytics implemented; funnels defined; regular analysis',
    orderIndex: 3,
    options: [
      { id: 'ba-023-1', label: 'Yes, comprehensive behavior analytics', value: 'full' },
      { id: 'ba-023-2', label: 'Basic page tracking', value: 'partial' },
      { id: 'ba-023-3', label: 'Limited analytics', value: 'minimal' },
      { id: 'ba-023-4', label: 'No behavior analytics', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-024',
    text: 'Do you conduct A/B testing for design decisions?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'quality_test',
    severity: 0.7,
    bestPractice: 'Run A/B tests with statistical significance; iterate based on data',
    practicalExplainer: 'A/B testing validates design changes with real user data.',
    standardRefs: 'Optimizely, VWO, Statistical Testing, Experimentation',
    acceptance: 'A/B testing capability; experiments run; decisions data-driven',
    orderIndex: 8,
    options: [
      { id: 'ba-024-1', label: 'Yes, regular A/B testing', value: 'full' },
      { id: 'ba-024-2', label: 'Occasional experiments', value: 'partial' },
      { id: 'ba-024-3', label: 'Basic testing capability', value: 'minimal' },
      { id: 'ba-024-4', label: 'No A/B testing', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// POLICY-TO-CONTROL MAPPING (11)
// ==========================================
export const policyControlQuestions: BAQuestion[] = [
  {
    id: 'q-ba-025',
    text: 'Do you map business requirements to security controls?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'compliance_policy',
    severity: 0.82,
    bestPractice: 'Map requirements to ISO 27001, NIST controls; trace implementation',
    practicalExplainer: 'Mapping ensures security requirements are addressed in design.',
    standardRefs: 'ISO 27001 Annex A, NIST 800-53, COBIT',
    acceptance: 'Control mapping exists; requirements traced; compliance verified',
    orderIndex: 3,
    options: [
      { id: 'ba-025-1', label: 'Yes, formal control mapping', value: 'full' },
      { id: 'ba-025-2', label: 'Some controls mapped', value: 'partial' },
      { id: 'ba-025-3', label: 'Informal security awareness', value: 'minimal' },
      { id: 'ba-025-4', label: 'No control mapping', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-026',
    text: 'Do you have privacy requirements documented (GDPR/CCPA)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'privacy_legal',
    severity: 0.85,
    bestPractice: 'Document privacy requirements by regulation; implement privacy by design',
    practicalExplainer: 'Privacy requirements ensure compliance with data protection laws.',
    standardRefs: 'GDPR Articles 5-7, 25, CCPA, Privacy by Design Principles',
    acceptance: 'Privacy requirements documented; DPIA completed; controls implemented',
    orderIndex: 3,
    options: [
      { id: 'ba-026-1', label: 'Yes, comprehensive privacy requirements', value: 'full' },
      { id: 'ba-026-2', label: 'Basic privacy requirements', value: 'partial' },
      { id: 'ba-026-3', label: 'Informal privacy awareness', value: 'minimal' },
      { id: 'ba-026-4', label: 'No privacy requirements', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-027',
    text: 'Do you document data classification requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'data_ai',
    severity: 0.79,
    bestPractice: 'Classify data by sensitivity; define handling requirements per level',
    practicalExplainer:
      'Data classification ensures appropriate protection for different data types.',
    standardRefs: 'ISO 27001:A.8.2, NIST 800-60, Data Classification Standards',
    acceptance: 'Classification scheme defined; data labeled; handling requirements documented',
    orderIndex: 4,
    options: [
      { id: 'ba-027-1', label: 'Yes, formal data classification', value: 'full' },
      { id: 'ba-027-2', label: 'Basic sensitivity levels', value: 'partial' },
      { id: 'ba-027-3', label: 'Informal understanding', value: 'minimal' },
      { id: 'ba-027-4', label: 'No data classification', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-028',
    text: 'Do you define retention and deletion requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'privacy_legal',
    severity: 0.78,
    bestPractice: 'Define retention periods by data type; implement automated deletion',
    practicalExplainer: 'Retention requirements ensure data is not kept longer than necessary.',
    standardRefs: 'GDPR Article 17, Records Retention, Data Lifecycle Management',
    acceptance: 'Retention periods defined; deletion implemented; audit trail exists',
    orderIndex: 4,
    options: [
      { id: 'ba-028-1', label: 'Yes, retention policy with automation', value: 'full' },
      { id: 'ba-028-2', label: 'Retention periods defined', value: 'partial' },
      { id: 'ba-028-3', label: 'Some retention awareness', value: 'minimal' },
      { id: 'ba-028-4', label: 'No retention policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-029',
    text: 'Do you document audit trail requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'compliance_policy',
    severity: 0.8,
    bestPractice: 'Define what events to log; ensure tamper-proof storage; define retention',
    practicalExplainer: 'Audit trails provide evidence for compliance and investigation.',
    standardRefs: 'ISO 27001:A.12.4, SOC 2 CC7.2, NIST 800-92',
    acceptance: 'Audit requirements documented; events defined; storage specified',
    orderIndex: 4,
    options: [
      { id: 'ba-029-1', label: 'Yes, comprehensive audit requirements', value: 'full' },
      { id: 'ba-029-2', label: 'Basic audit logging defined', value: 'partial' },
      { id: 'ba-029-3', label: 'Some logging awareness', value: 'minimal' },
      { id: 'ba-029-4', label: 'No audit requirements', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-030',
    text: 'Do you define consent management requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'privacy_legal',
    severity: 0.83,
    bestPractice: 'Define consent types; implement granular consent; track consent history',
    practicalExplainer: 'Consent management ensures lawful processing of personal data.',
    standardRefs: 'GDPR Articles 6-7, ePrivacy, Cookie Consent',
    acceptance: 'Consent requirements defined; granular consent designed; history tracked',
    orderIndex: 5,
    options: [
      { id: 'ba-030-1', label: 'Yes, comprehensive consent management', value: 'full' },
      { id: 'ba-030-2', label: 'Basic consent collection', value: 'partial' },
      { id: 'ba-030-3', label: 'Simple consent checkbox', value: 'minimal' },
      { id: 'ba-030-4', label: 'No consent management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-031',
    text: 'Do you document access control requirements (RBAC)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.81,
    bestPractice: 'Define roles and permissions; document access matrix; least privilege',
    practicalExplainer: 'Access control requirements ensure users only access what they need.',
    standardRefs: 'ISO 27001:A.9, RBAC Models, NIST 800-53 AC',
    acceptance: 'Roles defined; permissions documented; access matrix exists',
    orderIndex: 23,
    options: [
      { id: 'ba-031-1', label: 'Yes, comprehensive RBAC documented', value: 'full' },
      { id: 'ba-031-2', label: 'Basic roles defined', value: 'partial' },
      { id: 'ba-031-3', label: 'Admin/User distinction', value: 'minimal' },
      { id: 'ba-031-4', label: 'No access requirements', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-032',
    text: 'Do you map requirements to compliance frameworks?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'compliance_policy',
    severity: 0.79,
    bestPractice: 'Map to SOC 2, ISO 27001, HIPAA, PCI-DSS as applicable',
    practicalExplainer: 'Framework mapping ensures requirements address compliance needs.',
    standardRefs: 'SOC 2, ISO 27001, HIPAA, PCI-DSS, Compliance Mapping',
    acceptance: 'Applicable frameworks identified; requirements mapped; gaps addressed',
    orderIndex: 5,
    options: [
      { id: 'ba-032-1', label: 'Yes, mapped to frameworks', value: 'full' },
      { id: 'ba-032-2', label: 'Some framework awareness', value: 'partial' },
      { id: 'ba-032-3', label: 'Informal compliance understanding', value: 'minimal' },
      { id: 'ba-032-4', label: 'No framework mapping', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-033',
    text: 'Do you document integration requirements and APIs?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'requirements',
    severity: 0.75,
    bestPractice: 'Document API contracts; define integration patterns; specify SLAs',
    practicalExplainer: 'Integration requirements ensure systems work together correctly.',
    standardRefs: 'OpenAPI, API Design Guidelines, Integration Patterns',
    acceptance: 'API requirements documented; contracts defined; SLAs specified',
    orderIndex: 24,
    options: [
      { id: 'ba-033-1', label: 'Yes, comprehensive API documentation', value: 'full' },
      { id: 'ba-033-2', label: 'Basic integration requirements', value: 'partial' },
      { id: 'ba-033-3', label: 'Informal integration understanding', value: 'minimal' },
      { id: 'ba-033-4', label: 'No integration documentation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-034',
    text: 'Do you document disaster recovery requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'service_ops',
    severity: 0.77,
    bestPractice: 'Define RTO/RPO; document recovery procedures; specify backup requirements',
    practicalExplainer: 'DR requirements ensure the system can recover from disasters.',
    standardRefs: 'ISO 22301, NIST 800-34, Business Continuity',
    acceptance: 'RTO/RPO defined; backup requirements documented; DR procedures exist',
    orderIndex: 3,
    options: [
      { id: 'ba-034-1', label: 'Yes, DR requirements documented', value: 'full' },
      { id: 'ba-034-2', label: 'Basic RTO/RPO defined', value: 'partial' },
      { id: 'ba-034-3', label: 'Informal DR awareness', value: 'minimal' },
      { id: 'ba-034-4', label: 'No DR requirements', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-ba-035',
    text: 'Do you document SLA requirements for the system?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.BA,
    dimensionKey: 'service_ops',
    severity: 0.76,
    bestPractice: 'Define availability, performance, and support SLAs; track compliance',
    practicalExplainer: 'SLA requirements set expectations for system performance.',
    standardRefs: 'ITIL SLA Management, SLO/SLI, Site Reliability Engineering',
    acceptance: 'SLAs defined; metrics tracked; compliance reported',
    orderIndex: 4,
    options: [
      { id: 'ba-035-1', label: 'Yes, SLAs documented and tracked', value: 'full' },
      { id: 'ba-035-2', label: 'Basic availability targets', value: 'partial' },
      { id: 'ba-035-3', label: 'Informal expectations', value: 'minimal' },
      { id: 'ba-035-4', label: 'No SLA requirements', value: 'none' },
    ],
    isRequired: true,
  },
];

// Combined BA questions
export const baQuestions: BAQuestion[] = [
  ...requirementsQuestions,
  ...uxDesignQuestions,
  ...policyControlQuestions,
];

export default baQuestions;
