import { QuestionType, Persona } from '@prisma/client';

/**
 * CTO Questions - 40+ questions for Architecture, Security, Platform
 *
 * Categories:
 * - Architecture (15 questions)
 * - Security (15 questions)
 * - Platform/Infrastructure (10 questions)
 */

export interface CTOQuestion {
  id: string;
  text: string;
  type: QuestionType;
  persona: Persona;
  dimensionKey: string;
  severity: number;
  bestPractice: string;
  practicalExplainer: string;
  standardRefs: string;
  acceptance: string;
  helpText?: string;
  options?: { id: string; label: string; value: string }[];
  isRequired?: boolean;
  orderIndex: number;
}

// ==========================================
// ARCHITECTURE QUESTIONS (15)
// ==========================================
export const architectureQuestions: CTOQuestion[] = [
  {
    id: 'q-arch-007',
    text: 'Do you have API versioning and deprecation policies?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.75,
    bestPractice: 'Use semantic versioning with clear deprecation timelines and migration guides',
    practicalExplainer:
      'API versioning allows you to evolve your API without breaking existing integrations.',
    standardRefs: 'OpenAPI Spec 3.0, REST API Versioning Best Practices',
    acceptance:
      'API versioning documented; deprecation policy published; migration guides provided',
    orderIndex: 7,
    options: [
      { id: 'arch-007-1', label: 'Yes, formal versioning and deprecation policy', value: 'full' },
      { id: 'arch-007-2', label: 'Versioning exists, no formal policy', value: 'partial' },
      { id: 'arch-007-3', label: 'Informal versioning', value: 'minimal' },
      { id: 'arch-007-4', label: 'No versioning', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-008',
    text: 'Is your system designed for horizontal scalability?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.82,
    bestPractice: 'Design stateless services that can scale horizontally with load balancing',
    practicalExplainer:
      'Horizontal scaling adds more servers to handle load, rather than making one server bigger.',
    standardRefs: '12-Factor App, AWS Well-Architected Framework, Azure Architecture Center',
    acceptance:
      'Stateless services confirmed; auto-scaling configured; load tested at 3x expected load',
    orderIndex: 8,
    options: [
      { id: 'arch-008-1', label: 'Yes, fully horizontally scalable', value: 'full' },
      { id: 'arch-008-2', label: 'Mostly scalable, some bottlenecks', value: 'partial' },
      { id: 'arch-008-3', label: 'Limited scalability', value: 'minimal' },
      { id: 'arch-008-4', label: 'No scalability considerations', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-009',
    text: 'Do you implement circuit breakers for external dependencies?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.78,
    bestPractice: 'Implement circuit breakers with fallback mechanisms for all external calls',
    practicalExplainer: 'Circuit breakers prevent cascade failures when external services fail.',
    standardRefs: 'Release It! patterns, Microsoft Resilience patterns, Hystrix patterns',
    acceptance: 'Circuit breakers implemented; fallback behavior defined; health checks active',
    orderIndex: 9,
    options: [
      { id: 'arch-009-1', label: 'Yes, comprehensive circuit breakers', value: 'full' },
      { id: 'arch-009-2', label: 'Some critical services protected', value: 'partial' },
      { id: 'arch-009-3', label: 'Basic timeout handling', value: 'minimal' },
      { id: 'arch-009-4', label: 'No circuit breakers', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-010',
    text: 'Is your database schema properly normalized with appropriate indexes?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.76,
    bestPractice:
      'Normalize to 3NF minimum; create indexes for frequent queries; monitor query performance',
    practicalExplainer: 'Proper normalization reduces data redundancy; indexes speed up queries.',
    standardRefs: 'Database Normalization (3NF), SQL Performance Best Practices',
    acceptance:
      'Schema normalized to 3NF; query plans show index usage; no table scans on large tables',
    orderIndex: 10,
    options: [
      { id: 'arch-010-1', label: 'Yes, optimized schema with indexes', value: 'full' },
      { id: 'arch-010-2', label: 'Normalized but limited indexing', value: 'partial' },
      { id: 'arch-010-3', label: 'Basic normalization', value: 'minimal' },
      { id: 'arch-010-4', label: 'No schema optimization', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-011',
    text: 'Do you have a caching strategy implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.72,
    bestPractice:
      'Implement multi-layer caching (CDN, application, database) with proper invalidation',
    practicalExplainer: 'Caching reduces load on your backend and improves response times.',
    standardRefs: 'HTTP Caching RFC 7234, Redis Best Practices, CDN Caching Strategies',
    acceptance:
      'Caching implemented at appropriate layers; cache hit ratio >80%; invalidation tested',
    orderIndex: 11,
    options: [
      { id: 'arch-011-1', label: 'Yes, multi-layer caching strategy', value: 'full' },
      { id: 'arch-011-2', label: 'Application-level caching', value: 'partial' },
      { id: 'arch-011-3', label: 'Basic HTTP caching', value: 'minimal' },
      { id: 'arch-011-4', label: 'No caching', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-012',
    text: 'Is your system designed for graceful degradation?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.8,
    bestPractice: 'Design systems to provide reduced functionality rather than complete failure',
    practicalExplainer: 'Graceful degradation keeps core features working even when parts fail.',
    standardRefs: 'Netflix Resilience Engineering, AWS Fault Isolation, Azure Resiliency',
    acceptance:
      'Degradation modes documented; tested under failure conditions; user experience defined',
    orderIndex: 12,
    options: [
      { id: 'arch-012-1', label: 'Yes, graceful degradation designed', value: 'full' },
      { id: 'arch-012-2', label: 'Some services degrade gracefully', value: 'partial' },
      { id: 'arch-012-3', label: 'Basic error handling', value: 'minimal' },
      { id: 'arch-012-4', label: 'No graceful degradation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-013',
    text: 'Do you have service mesh or API gateway implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.68,
    bestPractice: 'Use API gateway for routing, rate limiting, and authentication at the edge',
    practicalExplainer:
      'API gateways centralize cross-cutting concerns like auth and rate limiting.',
    standardRefs: 'Kong, Istio, AWS API Gateway, Azure API Management',
    acceptance: 'API gateway configured; rate limiting active; authentication handled at gateway',
    orderIndex: 13,
    options: [
      { id: 'arch-013-1', label: 'Yes, API gateway with full features', value: 'full' },
      { id: 'arch-013-2', label: 'Basic API gateway/reverse proxy', value: 'partial' },
      { id: 'arch-013-3', label: 'Load balancer only', value: 'minimal' },
      { id: 'arch-013-4', label: 'No gateway layer', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-014',
    text: 'Is event-driven architecture used where appropriate?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.65,
    bestPractice: 'Use event sourcing and message queues for decoupled, scalable processing',
    practicalExplainer: 'Event-driven architecture enables loose coupling and async processing.',
    standardRefs: 'Event Sourcing patterns, Apache Kafka, Azure Service Bus, AWS SQS/SNS',
    acceptance: 'Message queue implemented; events documented; replay capability exists',
    orderIndex: 14,
    options: [
      { id: 'arch-014-1', label: 'Yes, event-driven with message queue', value: 'full' },
      { id: 'arch-014-2', label: 'Some async processing', value: 'partial' },
      { id: 'arch-014-3', label: 'Background jobs only', value: 'minimal' },
      { id: 'arch-014-4', label: 'All synchronous', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-015',
    text: 'Do you implement idempotent operations for critical endpoints?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.77,
    bestPractice: 'Make all mutating operations idempotent using idempotency keys',
    practicalExplainer:
      'Idempotent operations can be safely retried without duplicate side effects.',
    standardRefs: 'Stripe Idempotency, HTTP Methods RFC 7231, REST Best Practices',
    acceptance: 'All POST/PUT endpoints accept idempotency key; retries tested safe',
    orderIndex: 15,
    options: [
      { id: 'arch-015-1', label: 'Yes, all critical operations idempotent', value: 'full' },
      { id: 'arch-015-2', label: 'Payment/order operations idempotent', value: 'partial' },
      { id: 'arch-015-3', label: 'Some idempotency', value: 'minimal' },
      { id: 'arch-015-4', label: 'No idempotency considerations', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-016',
    text: 'Is your architecture documented with ADRs (Architecture Decision Records)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.7,
    bestPractice: 'Document all significant architecture decisions with context and consequences',
    practicalExplainer: 'ADRs capture why decisions were made, helping future team members.',
    standardRefs: 'ADR GitHub template, Michael Nygard ADR format, arc42',
    acceptance: 'ADR template in use; key decisions documented; reviewed in onboarding',
    orderIndex: 16,
    options: [
      { id: 'arch-016-1', label: 'Yes, comprehensive ADRs maintained', value: 'full' },
      { id: 'arch-016-2', label: 'Some key decisions documented', value: 'partial' },
      { id: 'arch-016-3', label: 'Informal documentation', value: 'minimal' },
      { id: 'arch-016-4', label: 'No architecture documentation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-017',
    text: 'Do you have a clear domain model with bounded contexts?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.72,
    bestPractice: 'Define bounded contexts using DDD; ensure clear context maps',
    practicalExplainer: 'Bounded contexts help manage complexity by isolating domain logic.',
    standardRefs: 'Domain-Driven Design (Eric Evans), Context Mapping patterns',
    acceptance: 'Domain model documented; bounded contexts defined; context map exists',
    orderIndex: 17,
    options: [
      { id: 'arch-017-1', label: 'Yes, DDD with bounded contexts', value: 'full' },
      { id: 'arch-017-2', label: 'Domain model exists, informal boundaries', value: 'partial' },
      { id: 'arch-017-3', label: 'Basic entity modeling', value: 'minimal' },
      { id: 'arch-017-4', label: 'No domain modeling', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-018',
    text: 'Is your system designed to handle partial failures?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.79,
    bestPractice: 'Use bulkhead pattern, timeouts, and retries with exponential backoff',
    practicalExplainer:
      'Partial failure handling prevents one failing component from taking down the system.',
    standardRefs: 'Microsoft Cloud Design Patterns, AWS Retry Behavior, Polly library',
    acceptance: 'Bulkheads implemented; retry policies defined; failure modes tested',
    orderIndex: 18,
    options: [
      { id: 'arch-018-1', label: 'Yes, comprehensive failure handling', value: 'full' },
      { id: 'arch-018-2', label: 'Basic retry logic implemented', value: 'partial' },
      { id: 'arch-018-3', label: 'Some timeout handling', value: 'minimal' },
      { id: 'arch-018-4', label: 'No failure handling', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-019',
    text: 'Do you implement feature flags for controlled rollouts?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.68,
    bestPractice: 'Use feature flags for gradual rollouts, A/B testing, and kill switches',
    practicalExplainer:
      'Feature flags let you release features gradually and turn them off quickly if needed.',
    standardRefs: 'LaunchDarkly, Azure App Configuration, OpenFeature',
    acceptance: 'Feature flag system in place; flags used for major features; kill switch tested',
    orderIndex: 19,
    options: [
      { id: 'arch-019-1', label: 'Yes, comprehensive feature flag system', value: 'full' },
      { id: 'arch-019-2', label: 'Basic feature toggles', value: 'partial' },
      { id: 'arch-019-3', label: 'Environment-based flags', value: 'minimal' },
      { id: 'arch-019-4', label: 'No feature flags', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-020',
    text: 'Is your API design following RESTful or GraphQL best practices?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.74,
    bestPractice: 'Follow REST maturity level 3 or implement GraphQL with proper schema design',
    practicalExplainer: 'Consistent API design makes your system easier to use and maintain.',
    standardRefs: 'REST API Design Rulebook, GraphQL Best Practices, OpenAPI Specification',
    acceptance: 'API style guide documented; consistent naming; proper HTTP methods/status codes',
    orderIndex: 20,
    options: [
      { id: 'arch-020-1', label: 'Yes, follows best practices strictly', value: 'full' },
      { id: 'arch-020-2', label: 'Mostly consistent API design', value: 'partial' },
      { id: 'arch-020-3', label: 'Inconsistent but functional', value: 'minimal' },
      { id: 'arch-020-4', label: 'No API design standards', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-arch-021',
    text: 'Do you have database replication and failover configured?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.84,
    bestPractice: 'Configure read replicas and automatic failover for database high availability',
    practicalExplainer: 'Database replication ensures your data survives hardware failures.',
    standardRefs: 'PostgreSQL Replication, AWS RDS Multi-AZ, Azure SQL Geo-Replication',
    acceptance: 'Replication configured; failover tested; RTO/RPO documented',
    orderIndex: 21,
    options: [
      { id: 'arch-021-1', label: 'Yes, multi-region replication with failover', value: 'full' },
      { id: 'arch-021-2', label: 'Single region with read replicas', value: 'partial' },
      { id: 'arch-021-3', label: 'Backup only, no replication', value: 'minimal' },
      { id: 'arch-021-4', label: 'No replication or failover', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// SECURITY QUESTIONS (15)
// ==========================================
export const securityQuestions: CTOQuestion[] = [
  {
    id: 'q-sec-001',
    text: 'Do you implement rate limiting and throttling?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.85,
    bestPractice: 'Implement rate limiting per user/IP with appropriate limits for each endpoint',
    practicalExplainer: 'Rate limiting prevents abuse and protects your system from DDoS attacks.',
    standardRefs: 'OWASP API Security Top 10, RFC 6585, API Rate Limiting Best Practices',
    acceptance: 'Rate limiting on all public endpoints; limits documented; alerts configured',
    orderIndex: 22,
    options: [
      { id: 'sec-001-1', label: 'Yes, comprehensive rate limiting', value: 'full' },
      { id: 'sec-001-2', label: 'Rate limiting on auth endpoints', value: 'partial' },
      { id: 'sec-001-3', label: 'Basic throttling', value: 'minimal' },
      { id: 'sec-001-4', label: 'No rate limiting', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-002',
    text: 'Do you use secure session management?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.88,
    bestPractice: 'Use secure, httpOnly cookies with proper expiration and rotation',
    practicalExplainer:
      'Secure session management prevents session hijacking and fixation attacks.',
    standardRefs: 'OWASP Session Management Cheat Sheet, OWASP ASVS V3.1',
    acceptance:
      'Sessions use secure cookies; idle timeout configured; session regeneration on auth',
    orderIndex: 23,
    options: [
      { id: 'sec-002-1', label: 'Yes, secure session management', value: 'full' },
      { id: 'sec-002-2', label: 'Basic session security', value: 'partial' },
      { id: 'sec-002-3', label: 'Sessions with some security', value: 'minimal' },
      { id: 'sec-002-4', label: 'No session security measures', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-003',
    text: 'Is Content Security Policy (CSP) implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.8,
    bestPractice: 'Implement strict CSP with report-uri to prevent XSS and data injection',
    practicalExplainer:
      'CSP tells browsers what sources of content are trusted, blocking XSS attacks.',
    standardRefs: 'OWASP CSP Cheat Sheet, W3C CSP Level 3, Mozilla CSP Guide',
    acceptance: 'CSP header present; no unsafe-inline; report-uri configured',
    orderIndex: 24,
    options: [
      { id: 'sec-003-1', label: 'Yes, strict CSP with reporting', value: 'full' },
      { id: 'sec-003-2', label: 'CSP with some unsafe rules', value: 'partial' },
      { id: 'sec-003-3', label: 'Report-only CSP', value: 'minimal' },
      { id: 'sec-003-4', label: 'No CSP', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-004',
    text: 'Do you implement CORS with proper configuration?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.78,
    bestPractice: 'Configure CORS with specific origins; never use wildcard in production',
    practicalExplainer: 'Proper CORS prevents unauthorized cross-origin requests to your API.',
    standardRefs: 'OWASP CORS, W3C CORS Specification, MDN CORS Guide',
    acceptance: 'CORS configured per environment; no wildcard origins in prod; preflight cached',
    orderIndex: 25,
    options: [
      { id: 'sec-004-1', label: 'Yes, properly configured CORS', value: 'full' },
      { id: 'sec-004-2', label: 'CORS with specific origins', value: 'partial' },
      { id: 'sec-004-3', label: 'Permissive CORS', value: 'minimal' },
      { id: 'sec-004-4', label: 'Wildcard CORS or disabled', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-005',
    text: 'Do you have vulnerability management process?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.9,
    bestPractice: 'Track CVEs, prioritize by severity, patch within SLA (critical: 48h)',
    practicalExplainer:
      'Vulnerability management ensures known security issues are addressed promptly.',
    standardRefs: 'NIST CVE, NVD, CVSS Scoring, ISO 27001:A.12.6',
    acceptance: 'Vulnerability tracking active; SLA defined; critical patches applied within SLA',
    orderIndex: 26,
    options: [
      { id: 'sec-005-1', label: 'Yes, formal vuln management', value: 'full' },
      { id: 'sec-005-2', label: 'Regular dependency updates', value: 'partial' },
      { id: 'sec-005-3', label: 'Ad-hoc patching', value: 'minimal' },
      { id: 'sec-005-4', label: 'No vulnerability management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-006',
    text: 'Is multi-factor authentication (MFA) supported?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.86,
    bestPractice: 'Implement TOTP or WebAuthn for all user accounts; enforce for admins',
    practicalExplainer: 'MFA adds a second layer of protection beyond passwords.',
    standardRefs: 'OWASP ASVS V2.8, NIST 800-63B, FIDO2/WebAuthn',
    acceptance: 'MFA available for all users; enforced for admin accounts; backup codes provided',
    orderIndex: 27,
    options: [
      { id: 'sec-006-1', label: 'Yes, MFA with TOTP/WebAuthn', value: 'full' },
      { id: 'sec-006-2', label: 'MFA for admin accounts only', value: 'partial' },
      { id: 'sec-006-3', label: 'Optional SMS 2FA', value: 'minimal' },
      { id: 'sec-006-4', label: 'No MFA support', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-007',
    text: 'Do you implement proper password policies?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.84,
    bestPractice: 'Require 12+ chars, check against breached passwords, use bcrypt/Argon2',
    practicalExplainer: 'Strong password policies prevent credential-based attacks.',
    standardRefs: 'NIST 800-63B, OWASP Password Storage, Have I Been Pwned API',
    acceptance: 'Min 12 chars; breached password check; bcrypt with cost 12+; no composition rules',
    orderIndex: 28,
    options: [
      { id: 'sec-007-1', label: 'Yes, NIST-compliant password policy', value: 'full' },
      { id: 'sec-007-2', label: 'Strong requirements without breach check', value: 'partial' },
      { id: 'sec-007-3', label: 'Basic length requirements', value: 'minimal' },
      { id: 'sec-007-4', label: 'No password requirements', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-008',
    text: 'Do you have security headers configured?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.76,
    bestPractice: 'Configure X-Frame-Options, X-Content-Type-Options, HSTS, Referrer-Policy',
    practicalExplainer: 'Security headers instruct browsers to enable additional protections.',
    standardRefs: 'OWASP Secure Headers, securityheaders.com, Mozilla Observatory',
    acceptance: 'All OWASP recommended headers present; A+ rating on securityheaders.com',
    orderIndex: 29,
    options: [
      { id: 'sec-008-1', label: 'Yes, all recommended headers', value: 'full' },
      { id: 'sec-008-2', label: 'Most security headers present', value: 'partial' },
      { id: 'sec-008-3', label: 'Some headers configured', value: 'minimal' },
      { id: 'sec-008-4', label: 'No security headers', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-009',
    text: 'Do you implement secure file upload handling?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.82,
    bestPractice:
      'Validate file types, scan for malware, store outside webroot, generate new names',
    practicalExplainer: 'Insecure file uploads can lead to remote code execution and malware.',
    standardRefs: 'OWASP File Upload Cheat Sheet, CWE-434, OWASP ASVS V12',
    acceptance: 'File type validation; virus scanning; files stored outside webroot; renamed files',
    orderIndex: 30,
    options: [
      { id: 'sec-009-1', label: 'Yes, comprehensive file upload security', value: 'full' },
      { id: 'sec-009-2', label: 'Validation and separate storage', value: 'partial' },
      { id: 'sec-009-3', label: 'Basic file type checks', value: 'minimal' },
      { id: 'sec-009-4', label: 'No file upload security', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-010',
    text: 'Do you have DDoS protection in place?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.83,
    bestPractice: 'Use CDN/WAF with DDoS protection; configure auto-scaling for traffic spikes',
    practicalExplainer:
      'DDoS attacks can take your service offline; protection ensures availability.',
    standardRefs: 'AWS Shield, Azure DDoS Protection, Cloudflare, NIST CSF PR.DS-4',
    acceptance: 'DDoS protection active; traffic anomaly detection; tested mitigation',
    orderIndex: 31,
    options: [
      { id: 'sec-010-1', label: 'Yes, enterprise DDoS protection', value: 'full' },
      { id: 'sec-010-2', label: 'CDN with basic DDoS protection', value: 'partial' },
      { id: 'sec-010-3', label: 'Rate limiting only', value: 'minimal' },
      { id: 'sec-010-4', label: 'No DDoS protection', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-011',
    text: 'Do you implement secure logging practices?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.79,
    bestPractice: 'Never log sensitive data; implement log integrity; centralize with SIEM',
    practicalExplainer: 'Secure logging helps detect attacks while protecting sensitive data.',
    standardRefs: 'OWASP Logging Cheat Sheet, CWE-117, ISO 27001:A.12.4',
    acceptance:
      'No PII/secrets in logs; centralized logging; log integrity verified; retention policy',
    orderIndex: 32,
    options: [
      { id: 'sec-011-1', label: 'Yes, secure centralized logging', value: 'full' },
      { id: 'sec-011-2', label: 'Centralized but some sensitive data', value: 'partial' },
      { id: 'sec-011-3', label: 'Basic logging without security', value: 'minimal' },
      { id: 'sec-011-4', label: 'No logging security measures', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-012',
    text: 'Is JWT/token security properly implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.86,
    bestPractice: 'Use RS256/ES256; short expiry with refresh tokens; validate all claims',
    practicalExplainer: 'Insecure token handling can lead to authentication bypass.',
    standardRefs: 'RFC 7519 JWT, OWASP JWT Security, Auth0 JWT Best Practices',
    acceptance:
      'Asymmetric signing; 15min access token expiry; all claims validated; refresh rotation',
    orderIndex: 33,
    options: [
      { id: 'sec-012-1', label: 'Yes, secure JWT implementation', value: 'full' },
      { id: 'sec-012-2', label: 'HS256 with proper validation', value: 'partial' },
      { id: 'sec-012-3', label: 'Basic JWT with long expiry', value: 'minimal' },
      { id: 'sec-012-4', label: 'Insecure token handling', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-013',
    text: 'Do you perform regular security assessments?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.88,
    bestPractice: 'Annual penetration testing; quarterly vulnerability scans; bug bounty program',
    practicalExplainer: 'Regular assessments find vulnerabilities before attackers do.',
    standardRefs: 'PTES, OWASP Testing Guide, NIST 800-115, ISO 27001:A.18.2',
    acceptance: 'Annual pentest; quarterly scans; findings tracked and remediated',
    orderIndex: 34,
    options: [
      { id: 'sec-013-1', label: 'Yes, regular pentests and bug bounty', value: 'full' },
      { id: 'sec-013-2', label: 'Annual penetration testing', value: 'partial' },
      { id: 'sec-013-3', label: 'Occasional security reviews', value: 'minimal' },
      { id: 'sec-013-4', label: 'No security assessments', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-014',
    text: 'Do you have secrets rotation implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.81,
    bestPractice: 'Automate secrets rotation; use short-lived credentials where possible',
    practicalExplainer:
      'Secrets rotation limits the window of exposure if credentials are compromised.',
    standardRefs: 'HashiCorp Vault, AWS Secrets Manager, Azure Key Vault, NIST 800-57',
    acceptance:
      'Automated rotation for DB credentials; API keys rotated quarterly; no long-lived secrets',
    orderIndex: 35,
    options: [
      { id: 'sec-014-1', label: 'Yes, automated secrets rotation', value: 'full' },
      { id: 'sec-014-2', label: 'Manual rotation with schedule', value: 'partial' },
      { id: 'sec-014-3', label: 'Ad-hoc rotation', value: 'minimal' },
      { id: 'sec-014-4', label: 'No secrets rotation', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-sec-015',
    text: 'Is API authentication properly secured?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'arch_sec',
    severity: 0.89,
    bestPractice: 'Use OAuth 2.0 + PKCE; validate scopes; implement proper token storage',
    practicalExplainer: 'Secure API auth prevents unauthorized access to your services.',
    standardRefs: 'OAuth 2.0 RFC 6749, PKCE RFC 7636, OWASP API Security',
    acceptance:
      'OAuth 2.0 with PKCE; scope validation; secure token storage; refresh token rotation',
    orderIndex: 36,
    options: [
      { id: 'sec-015-1', label: 'Yes, OAuth 2.0 with PKCE', value: 'full' },
      { id: 'sec-015-2', label: 'OAuth 2.0 without PKCE', value: 'partial' },
      { id: 'sec-015-3', label: 'API keys only', value: 'minimal' },
      { id: 'sec-015-4', label: 'No proper API auth', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// PLATFORM QUESTIONS (10)
// ==========================================
export const platformQuestions: CTOQuestion[] = [
  {
    id: 'q-plat-001',
    text: 'Do you have multi-environment deployment strategy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.8,
    bestPractice: 'Maintain dev/staging/prod environments with promotion pipeline',
    practicalExplainer: 'Multiple environments allow testing changes before they reach production.',
    standardRefs: '12-Factor App, GitOps, Progressive Delivery',
    acceptance: 'Separate dev/staging/prod; automated promotion; environment parity',
    orderIndex: 6,
    options: [
      { id: 'plat-001-1', label: 'Yes, full environment strategy', value: 'full' },
      { id: 'plat-001-2', label: 'Dev and prod only', value: 'partial' },
      { id: 'plat-001-3', label: 'Manual environment management', value: 'minimal' },
      { id: 'plat-001-4', label: 'Single environment', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-002',
    text: 'Is your platform observability stack complete?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.82,
    bestPractice: 'Implement metrics, logs, and traces (three pillars of observability)',
    practicalExplainer:
      'Complete observability helps you understand system behavior and debug issues.',
    standardRefs: 'OpenTelemetry, Grafana Stack, ELK/EFK, Datadog, New Relic',
    acceptance: 'Metrics, logs, traces collected; dashboards configured; SLO monitoring',
    orderIndex: 7,
    options: [
      { id: 'plat-002-1', label: 'Yes, full observability stack', value: 'full' },
      { id: 'plat-002-2', label: 'Metrics and logs only', value: 'partial' },
      { id: 'plat-002-3', label: 'Logs only', value: 'minimal' },
      { id: 'plat-002-4', label: 'No observability', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-003',
    text: 'Do you have disaster recovery procedures?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.88,
    bestPractice: 'Document and test DR procedures; define RTO/RPO; multi-region capability',
    practicalExplainer: 'DR ensures you can recover from catastrophic failures quickly.',
    standardRefs: 'ISO 22301, NIST CSF PR.IP-9, AWS DR, Azure BCDR',
    acceptance: 'DR plan documented; RTO/RPO defined; tested within last 6 months',
    orderIndex: 8,
    options: [
      { id: 'plat-003-1', label: 'Yes, tested DR with multi-region', value: 'full' },
      { id: 'plat-003-2', label: 'DR plan with backups', value: 'partial' },
      { id: 'plat-003-3', label: 'Backups only', value: 'minimal' },
      { id: 'plat-003-4', label: 'No DR planning', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-004',
    text: 'Is your deployment zero-downtime?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.78,
    bestPractice: 'Use rolling deployments, blue-green, or canary for zero-downtime releases',
    practicalExplainer: 'Zero-downtime deployments ensure users are never interrupted by releases.',
    standardRefs: 'Kubernetes Rolling Updates, AWS ECS, Azure Container Apps, Spinnaker',
    acceptance: 'Zero-downtime verified; deployment tested; health checks configured',
    orderIndex: 9,
    options: [
      { id: 'plat-004-1', label: 'Yes, zero-downtime deployments', value: 'full' },
      { id: 'plat-004-2', label: 'Minimal downtime (<1 min)', value: 'partial' },
      { id: 'plat-004-3', label: 'Maintenance window required', value: 'minimal' },
      { id: 'plat-004-4', label: 'Significant downtime', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-005',
    text: 'Do you have automated backup and restore procedures?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.86,
    bestPractice:
      'Automate daily backups; test restores monthly; encrypt backups; off-site storage',
    practicalExplainer: 'Backups are useless if you cannot restore from them.',
    standardRefs: 'ISO 27001:A.12.3, NIST CSF PR.IP-4, 3-2-1 Backup Rule',
    acceptance: 'Automated backups; monthly restore tests; encrypted; off-site copies',
    orderIndex: 10,
    options: [
      { id: 'plat-005-1', label: 'Yes, automated with tested restores', value: 'full' },
      { id: 'plat-005-2', label: 'Automated backups, untested restores', value: 'partial' },
      { id: 'plat-005-3', label: 'Manual backups', value: 'minimal' },
      { id: 'plat-005-4', label: 'No backup procedures', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-006',
    text: 'Is resource utilization monitored and optimized?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.72,
    bestPractice: 'Monitor CPU, memory, storage; right-size resources; auto-scale based on demand',
    practicalExplainer: 'Resource optimization reduces costs while maintaining performance.',
    standardRefs: 'FinOps, AWS Cost Explorer, Azure Advisor, Kubernetes VPA/HPA',
    acceptance:
      'Resource dashboards active; right-sizing recommendations applied; auto-scaling configured',
    orderIndex: 11,
    options: [
      { id: 'plat-006-1', label: 'Yes, optimized with auto-scaling', value: 'full' },
      { id: 'plat-006-2', label: 'Monitored with manual optimization', value: 'partial' },
      { id: 'plat-006-3', label: 'Basic monitoring only', value: 'minimal' },
      { id: 'plat-006-4', label: 'No resource monitoring', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-007',
    text: 'Do you have infrastructure security scanning?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.84,
    bestPractice: 'Scan IaC for misconfigurations; run CIS benchmarks; remediate findings',
    practicalExplainer: 'Infrastructure scanning catches misconfigurations before deployment.',
    standardRefs: 'CIS Benchmarks, Checkov, tfsec, AWS Security Hub, Azure Defender',
    acceptance: 'IaC scanning in CI; CIS compliance >90%; findings tracked and remediated',
    orderIndex: 12,
    options: [
      { id: 'plat-007-1', label: 'Yes, comprehensive IaC security scanning', value: 'full' },
      { id: 'plat-007-2', label: 'IaC scanning without enforcement', value: 'partial' },
      { id: 'plat-007-3', label: 'Manual security reviews', value: 'minimal' },
      { id: 'plat-007-4', label: 'No infrastructure security scanning', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-008',
    text: 'Is network segmentation properly implemented?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.83,
    bestPractice: 'Segment networks by trust level; implement micro-segmentation for services',
    practicalExplainer: 'Network segmentation limits blast radius if one system is compromised.',
    standardRefs: 'NIST 800-125B, CIS Controls v8 12, Zero Trust Architecture',
    acceptance: 'VNets/subnets per tier; NSGs configured; east-west traffic controlled',
    orderIndex: 13,
    options: [
      { id: 'plat-008-1', label: 'Yes, micro-segmentation implemented', value: 'full' },
      { id: 'plat-008-2', label: 'Basic subnet segmentation', value: 'partial' },
      { id: 'plat-008-3', label: 'Single VNet with security groups', value: 'minimal' },
      { id: 'plat-008-4', label: 'Flat network', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-009',
    text: 'Do you implement GitOps for infrastructure?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.74,
    bestPractice: 'Store all infrastructure config in Git; use pull-based deployment',
    practicalExplainer: 'GitOps provides audit trail and enables infrastructure as code review.',
    standardRefs: 'GitOps Principles, ArgoCD, Flux, Terraform Cloud',
    acceptance: 'All infra in Git; PR-based changes; automated sync; drift detection',
    orderIndex: 14,
    options: [
      { id: 'plat-009-1', label: 'Yes, full GitOps with drift detection', value: 'full' },
      { id: 'plat-009-2', label: 'IaC in Git with manual apply', value: 'partial' },
      { id: 'plat-009-3', label: 'Some config in Git', value: 'minimal' },
      { id: 'plat-009-4', label: 'No GitOps', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-plat-010',
    text: 'Is your platform SOC 2 / ISO 27001 ready?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.CTO,
    dimensionKey: 'devops_iac',
    severity: 0.85,
    bestPractice:
      'Implement controls for SOC 2 Type II or ISO 27001; maintain evidence continuously',
    practicalExplainer: 'Compliance readiness enables you to serve enterprise customers.',
    standardRefs: 'SOC 2 Trust Service Criteria, ISO 27001:2022, AICPA',
    acceptance:
      'Controls mapped to framework; evidence collection automated; gap analysis complete',
    orderIndex: 15,
    options: [
      { id: 'plat-010-1', label: 'Yes, certified or audit-ready', value: 'full' },
      { id: 'plat-010-2', label: 'Controls implemented, no audit', value: 'partial' },
      { id: 'plat-010-3', label: 'Gap analysis started', value: 'minimal' },
      { id: 'plat-010-4', label: 'No compliance work', value: 'none' },
    ],
    isRequired: true,
  },
];

// Combined CTO questions
export const ctoQuestions: CTOQuestion[] = [
  ...architectureQuestions,
  ...securityQuestions,
  ...platformQuestions,
];

export default ctoQuestions;
