import { QuestionType, Persona } from '@prisma/client';

/**
 * Policy Writer Questions - 40+ questions for Compliance, Auditability, Governance
 *
 * Categories:
 * - Compliance & Regulatory (14 questions)
 * - Auditability & Controls (13 questions)
 * - Governance & Policies (13 questions)
 */

export interface PolicyQuestion {
  id: string;
  text: string;
  type: QuestionType;
  persona: Persona;
  dimensionKey: string;
  severity: number;
  bestPractice: string;
  practicalExplainer: string;
  standardRefs: string;
  acceptance: string;
  helpText?: string;
  options?: { id: string; label: string; value: string }[];
  isRequired?: boolean;
  orderIndex: number;
}

// ==========================================
// COMPLIANCE & REGULATORY (14)
// ==========================================
export const complianceQuestions: PolicyQuestion[] = [
  {
    id: 'q-pol-001',
    text: 'Have you identified all applicable laws and regulations?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.88,
    bestPractice: 'Create regulatory register; map to controls; update annually',
    practicalExplainer: 'Knowing applicable regulations is the foundation of compliance.',
    standardRefs: 'ISO 27001:A.18.1, NIST CSF ID.GV-3, Regulatory Compliance',
    acceptance: 'Regulatory register exists; annually updated; controls mapped',
    orderIndex: 6,
    options: [
      { id: 'pol-001-1', label: 'Yes, comprehensive regulatory register', value: 'full' },
      { id: 'pol-001-2', label: 'Key regulations identified', value: 'partial' },
      { id: 'pol-001-3', label: 'Basic awareness', value: 'minimal' },
      { id: 'pol-001-4', label: 'Regulations not identified', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-002',
    text: 'Do you have a Data Protection Impact Assessment (DPIA) process?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.86,
    bestPractice: 'Conduct DPIA for high-risk processing; document and mitigate risks',
    practicalExplainer: 'DPIAs identify and minimize data protection risks.',
    standardRefs: 'GDPR Article 35, ICO DPIA Guidance, Privacy by Design',
    acceptance: 'DPIA process documented; high-risk activities assessed; mitigations in place',
    orderIndex: 6,
    options: [
      { id: 'pol-002-1', label: 'Yes, formal DPIA process', value: 'full' },
      { id: 'pol-002-2', label: 'Ad-hoc privacy assessments', value: 'partial' },
      { id: 'pol-002-3', label: 'Basic privacy awareness', value: 'minimal' },
      { id: 'pol-002-4', label: 'No DPIA process', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-003',
    text: 'Do you have a privacy notice that meets regulatory requirements?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.85,
    bestPractice: 'Clear, accessible privacy notice with all required information',
    practicalExplainer: 'Privacy notices inform users how their data is handled.',
    standardRefs: 'GDPR Articles 13-14, CCPA Notice Requirements, FTC Guidelines',
    acceptance: 'Privacy notice published; meets all requirements; regularly reviewed',
    orderIndex: 7,
    options: [
      { id: 'pol-003-1', label: 'Yes, compliant privacy notice', value: 'full' },
      { id: 'pol-003-2', label: 'Basic privacy notice', value: 'partial' },
      { id: 'pol-003-3', label: 'Incomplete notice', value: 'minimal' },
      { id: 'pol-003-4', label: 'No privacy notice', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-004',
    text: 'Do you maintain Records of Processing Activities (ROPA)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.83,
    bestPractice: 'Document all processing activities; legal basis; data flows',
    practicalExplainer: 'ROPA is a legal requirement showing what data you process and why.',
    standardRefs: 'GDPR Article 30, Data Mapping, Processing Registry',
    acceptance: 'ROPA maintained; all processing documented; regularly updated',
    orderIndex: 8,
    options: [
      { id: 'pol-004-1', label: 'Yes, comprehensive ROPA', value: 'full' },
      { id: 'pol-004-2', label: 'Basic processing records', value: 'partial' },
      { id: 'pol-004-3', label: 'Informal data awareness', value: 'minimal' },
      { id: 'pol-004-4', label: 'No ROPA', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-005',
    text: 'Do you have data breach notification procedures?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.9,
    bestPractice: 'Document breach response; notify within 72 hours; templates ready',
    practicalExplainer: 'Breach notification is a legal requirement with tight timelines.',
    standardRefs: 'GDPR Article 33-34, CCPA Breach Notice, State Breach Laws',
    acceptance: 'Procedure documented; templates ready; 72-hour capability tested',
    orderIndex: 7,
    options: [
      { id: 'pol-005-1', label: 'Yes, breach notification ready', value: 'full' },
      { id: 'pol-005-2', label: 'Basic procedure exists', value: 'partial' },
      { id: 'pol-005-3', label: 'Informal process', value: 'minimal' },
      { id: 'pol-005-4', label: 'No breach procedures', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-006',
    text: 'Do you have a Data Protection Officer (DPO) or equivalent?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.78,
    bestPractice: 'Appoint DPO if required; ensure independence and expertise',
    practicalExplainer: 'A DPO oversees data protection compliance and is required in some cases.',
    standardRefs: 'GDPR Articles 37-39, DPO Requirements, Privacy Leadership',
    acceptance: 'DPO appointed (if required); responsibilities defined; independence ensured',
    orderIndex: 9,
    options: [
      { id: 'pol-006-1', label: 'Yes, DPO appointed', value: 'full' },
      { id: 'pol-006-2', label: 'Privacy lead (not formal DPO)', value: 'partial' },
      { id: 'pol-006-3', label: 'Ad-hoc privacy responsibility', value: 'minimal' },
      { id: 'pol-006-4', label: 'No DPO or privacy lead', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-007',
    text: 'Do you have international data transfer mechanisms?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.84,
    bestPractice: 'Use SCCs, BCRs, or adequacy; conduct transfer impact assessments',
    practicalExplainer: 'International transfers require legal mechanisms under GDPR.',
    standardRefs: 'GDPR Chapter V, SCCs, BCRs, Data Transfer Impact Assessment',
    acceptance: 'Transfer mechanisms in place; TIA conducted; documented',
    orderIndex: 10,
    options: [
      { id: 'pol-007-1', label: 'Yes, transfer mechanisms documented', value: 'full' },
      { id: 'pol-007-2', label: 'SCCs in place', value: 'partial' },
      { id: 'pol-007-3', label: 'Transfer awareness', value: 'minimal' },
      { id: 'pol-007-4', label: 'No transfer mechanisms', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-008',
    text: 'Do you have third-party risk management for data processors?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.82,
    bestPractice: 'Due diligence on processors; DPA contracts; regular reviews',
    practicalExplainer: 'You are responsible for ensuring processors handle data properly.',
    standardRefs: 'GDPR Article 28, Vendor Risk Management, Third-Party Due Diligence',
    acceptance: 'Processor register exists; DPAs signed; annual reviews conducted',
    orderIndex: 8,
    options: [
      { id: 'pol-008-1', label: 'Yes, formal third-party management', value: 'full' },
      { id: 'pol-008-2', label: 'DPAs with key vendors', value: 'partial' },
      { id: 'pol-008-3', label: 'Basic vendor contracts', value: 'minimal' },
      { id: 'pol-008-4', label: 'No processor management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-009',
    text: 'Do you conduct regular compliance assessments?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.81,
    bestPractice: 'Annual compliance review; gap analysis; remediation tracking',
    practicalExplainer: 'Regular assessments catch compliance gaps before auditors do.',
    standardRefs: 'ISO 27001:A.18.2, Internal Audit, Compliance Review',
    acceptance: 'Annual assessments conducted; gaps identified; remediation tracked',
    orderIndex: 9,
    options: [
      { id: 'pol-009-1', label: 'Yes, regular compliance assessments', value: 'full' },
      { id: 'pol-009-2', label: 'Periodic reviews', value: 'partial' },
      { id: 'pol-009-3', label: 'Ad-hoc compliance checks', value: 'minimal' },
      { id: 'pol-009-4', label: 'No compliance assessments', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-010',
    text: 'Do you track regulatory changes and updates?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.76,
    bestPractice: 'Subscribe to regulatory updates; assess impact; update controls',
    practicalExplainer: 'Regulations change; staying current prevents compliance gaps.',
    standardRefs: 'Regulatory Monitoring, Legal Updates, Compliance Intelligence',
    acceptance: 'Monitoring process exists; changes assessed; controls updated',
    orderIndex: 10,
    options: [
      { id: 'pol-010-1', label: 'Yes, systematic monitoring', value: 'full' },
      { id: 'pol-010-2', label: 'Periodic monitoring', value: 'partial' },
      { id: 'pol-010-3', label: 'Informal awareness', value: 'minimal' },
      { id: 'pol-010-4', label: 'No regulatory monitoring', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-011',
    text: 'Do you have lawful basis documented for all data processing?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.87,
    bestPractice: 'Document lawful basis per processing activity; review regularly',
    practicalExplainer: 'Every data processing activity needs a valid legal basis.',
    standardRefs: 'GDPR Article 6, Lawful Basis for Processing, Legitimate Interest Assessment',
    acceptance: 'Lawful basis documented for all processing; LIA where applicable',
    orderIndex: 11,
    options: [
      { id: 'pol-011-1', label: 'Yes, lawful basis documented', value: 'full' },
      { id: 'pol-011-2', label: 'Key processing documented', value: 'partial' },
      { id: 'pol-011-3', label: 'Basic understanding', value: 'minimal' },
      { id: 'pol-011-4', label: 'Lawful basis not documented', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-012',
    text: 'Do you have cookie consent and tracking compliance?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.79,
    bestPractice: 'Cookie banner with granular consent; honor preferences; audit trackers',
    practicalExplainer: 'Cookie consent is required under ePrivacy and GDPR.',
    standardRefs: 'ePrivacy Directive, GDPR Cookie Consent, IAB TCF',
    acceptance: 'Cookie banner compliant; consent recorded; preferences honored',
    orderIndex: 12,
    options: [
      { id: 'pol-012-1', label: 'Yes, compliant cookie consent', value: 'full' },
      { id: 'pol-012-2', label: 'Basic cookie notice', value: 'partial' },
      { id: 'pol-012-3', label: 'Cookie banner exists', value: 'minimal' },
      { id: 'pol-012-4', label: 'No cookie compliance', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-013',
    text: 'Do you have terms of service and acceptable use policies?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.75,
    bestPractice: 'Clear ToS reviewed by legal; acceptable use defined; update process',
    practicalExplainer: 'Terms of service protect your business and set user expectations.',
    standardRefs: 'Contract Law, Terms of Service, Acceptable Use Policy',
    acceptance: 'ToS/AUP published; legally reviewed; update process exists',
    orderIndex: 13,
    options: [
      { id: 'pol-013-1', label: 'Yes, comprehensive ToS/AUP', value: 'full' },
      { id: 'pol-013-2', label: 'Basic terms exist', value: 'partial' },
      { id: 'pol-013-3', label: 'Informal terms', value: 'minimal' },
      { id: 'pol-013-4', label: 'No ToS/AUP', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-014',
    text: 'Do you have intellectual property (IP) protection measures?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'privacy_legal',
    severity: 0.72,
    bestPractice: 'Register trademarks; protect trade secrets; employee IP agreements',
    practicalExplainer: 'IP protection safeguards your competitive advantages.',
    standardRefs: 'IP Law, Trademark Registration, Trade Secret Protection, NDA',
    acceptance: 'Trademarks registered; IP agreements signed; trade secrets identified',
    orderIndex: 14,
    options: [
      { id: 'pol-014-1', label: 'Yes, comprehensive IP protection', value: 'full' },
      { id: 'pol-014-2', label: 'Some IP measures', value: 'partial' },
      { id: 'pol-014-3', label: 'Basic awareness', value: 'minimal' },
      { id: 'pol-014-4', label: 'No IP protection', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// AUDITABILITY & CONTROLS (13)
// ==========================================
export const auditabilityQuestions: PolicyQuestion[] = [
  {
    id: 'q-pol-015',
    text: 'Do you maintain immutable audit logs?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.85,
    bestPractice: 'Tamper-proof logging; WORM storage; defined retention',
    practicalExplainer: 'Immutable logs provide trustworthy evidence for investigations.',
    standardRefs: 'ISO 27001:A.12.4, SOC 2 CC7.2, NIST 800-92',
    acceptance: 'Audit logs immutable; integrity verified; retention met',
    orderIndex: 11,
    options: [
      { id: 'pol-015-1', label: 'Yes, immutable audit logs', value: 'full' },
      { id: 'pol-015-2', label: 'Protected logs without WORM', value: 'partial' },
      { id: 'pol-015-3', label: 'Basic logging', value: 'minimal' },
      { id: 'pol-015-4', label: 'No audit logging', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-016',
    text: 'Do you have evidence collection procedures for audits?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.8,
    bestPractice: 'Document evidence sources; automate collection; maintain readiness',
    practicalExplainer: 'Audit preparation reduces disruption when auditors arrive.',
    standardRefs: 'ISO 27001:A.18.2, Audit Evidence, SOC 2 Readiness',
    acceptance: 'Evidence sources documented; collection automated; always audit-ready',
    orderIndex: 12,
    options: [
      { id: 'pol-016-1', label: 'Yes, automated evidence collection', value: 'full' },
      { id: 'pol-016-2', label: 'Manual collection process', value: 'partial' },
      { id: 'pol-016-3', label: 'Ad-hoc evidence gathering', value: 'minimal' },
      { id: 'pol-016-4', label: 'No evidence procedures', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-017',
    text: 'Do you have a control framework mapped to standards?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.83,
    bestPractice: 'Map controls to ISO 27001, SOC 2, NIST; maintain control descriptions',
    practicalExplainer: 'Control frameworks ensure comprehensive security coverage.',
    standardRefs: 'ISO 27001 Annex A, SOC 2 TSC, NIST 800-53',
    acceptance: 'Control framework documented; mapped to standards; owners assigned',
    orderIndex: 13,
    options: [
      { id: 'pol-017-1', label: 'Yes, comprehensive control framework', value: 'full' },
      { id: 'pol-017-2', label: 'Basic controls mapped', value: 'partial' },
      { id: 'pol-017-3', label: 'Some controls defined', value: 'minimal' },
      { id: 'pol-017-4', label: 'No control framework', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-018',
    text: 'Do you conduct regular control testing?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.82,
    bestPractice: 'Test key controls quarterly; document results; remediate findings',
    practicalExplainer: 'Control testing verifies that controls work as intended.',
    standardRefs: 'ISO 27001:9.1, SOC 2 Testing, NIST Control Assessment',
    acceptance: 'Controls tested regularly; results documented; findings remediated',
    orderIndex: 14,
    options: [
      { id: 'pol-018-1', label: 'Yes, regular control testing', value: 'full' },
      { id: 'pol-018-2', label: 'Annual testing', value: 'partial' },
      { id: 'pol-018-3', label: 'Ad-hoc testing', value: 'minimal' },
      { id: 'pol-018-4', label: 'No control testing', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-019',
    text: 'Do you have internal audit capability?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.77,
    bestPractice: 'Conduct internal audits annually; independent auditor; track findings',
    practicalExplainer: 'Internal audits find issues before external auditors do.',
    standardRefs: 'ISO 27001:9.2, Internal Audit Standards, IIA',
    acceptance: 'Internal audits conducted; independent; findings tracked',
    orderIndex: 15,
    options: [
      { id: 'pol-019-1', label: 'Yes, formal internal audit program', value: 'full' },
      { id: 'pol-019-2', label: 'Periodic internal reviews', value: 'partial' },
      { id: 'pol-019-3', label: 'Ad-hoc self-assessments', value: 'minimal' },
      { id: 'pol-019-4', label: 'No internal audit', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-020',
    text: 'Do you have exception management for policy deviations?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.74,
    bestPractice: 'Document exceptions; approval workflow; time-limited; tracked',
    practicalExplainer: 'Exception management allows controlled policy deviations.',
    standardRefs: 'Exception Management, Risk Acceptance, Compensating Controls',
    acceptance: 'Exception process exists; approvals documented; expiry tracked',
    orderIndex: 16,
    options: [
      { id: 'pol-020-1', label: 'Yes, formal exception management', value: 'full' },
      { id: 'pol-020-2', label: 'Basic exception tracking', value: 'partial' },
      { id: 'pol-020-3', label: 'Informal exceptions', value: 'minimal' },
      { id: 'pol-020-4', label: 'No exception management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-021',
    text: 'Do you track key risk indicators (KRIs)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.76,
    bestPractice: 'Define KRIs; set thresholds; alert on breaches; report regularly',
    practicalExplainer: 'KRIs provide early warning of emerging risks.',
    standardRefs: 'COSO ERM, ISO 31000, Risk Indicators',
    acceptance: 'KRIs defined; thresholds set; regular reporting',
    orderIndex: 17,
    options: [
      { id: 'pol-021-1', label: 'Yes, KRI dashboard active', value: 'full' },
      { id: 'pol-021-2', label: 'Some KRIs tracked', value: 'partial' },
      { id: 'pol-021-3', label: 'Basic risk metrics', value: 'minimal' },
      { id: 'pol-021-4', label: 'No KRI tracking', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-022',
    text: 'Do you have segregation of duties controls?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.81,
    bestPractice: 'Identify conflicting duties; enforce separation; detect violations',
    practicalExplainer: 'SoD prevents fraud by requiring multiple people for sensitive tasks.',
    standardRefs: 'SOX Controls, COSO, Segregation of Duties Matrix',
    acceptance: 'SoD matrix defined; controls enforced; violations detected',
    orderIndex: 18,
    options: [
      { id: 'pol-022-1', label: 'Yes, formal SoD controls', value: 'full' },
      { id: 'pol-022-2', label: 'Basic separation enforced', value: 'partial' },
      { id: 'pol-022-3', label: 'Some awareness', value: 'minimal' },
      { id: 'pol-022-4', label: 'No SoD controls', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-023',
    text: 'Do you have periodic access reviews?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.83,
    bestPractice: 'Quarterly access reviews; manager attestation; automated revocation',
    practicalExplainer: 'Access reviews ensure users still need their permissions.',
    standardRefs: 'ISO 27001:A.9.2, SOC 2 CC6.2, Access Certification',
    acceptance: 'Quarterly reviews conducted; attestation documented; access revoked',
    orderIndex: 19,
    options: [
      { id: 'pol-023-1', label: 'Yes, regular access reviews', value: 'full' },
      { id: 'pol-023-2', label: 'Annual reviews', value: 'partial' },
      { id: 'pol-023-3', label: 'Ad-hoc reviews', value: 'minimal' },
      { id: 'pol-023-4', label: 'No access reviews', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-024',
    text: 'Do you have change management controls?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.8,
    bestPractice: 'CAB approval; testing required; rollback plans; documented',
    practicalExplainer: 'Change management prevents unauthorized or untested changes.',
    standardRefs: 'ITIL Change Management, ISO 27001:A.12.1.2, SOC 2 CC8',
    acceptance: 'Change process documented; approvals required; tested; audit trail',
    orderIndex: 20,
    options: [
      { id: 'pol-024-1', label: 'Yes, formal change management', value: 'full' },
      { id: 'pol-024-2', label: 'Basic change tracking', value: 'partial' },
      { id: 'pol-024-3', label: 'Informal change process', value: 'minimal' },
      { id: 'pol-024-4', label: 'No change management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-025',
    text: 'Do you track remediation of audit findings?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.79,
    bestPractice: 'Log all findings; assign owners; track to closure; escalate overdue',
    practicalExplainer: 'Tracking findings ensures issues are actually resolved.',
    standardRefs: 'Audit Remediation, Finding Management, GRC Platforms',
    acceptance: 'Findings logged; owners assigned; tracked; overdue escalated',
    orderIndex: 21,
    options: [
      { id: 'pol-025-1', label: 'Yes, systematic finding tracking', value: 'full' },
      { id: 'pol-025-2', label: 'Basic tracking', value: 'partial' },
      { id: 'pol-025-3', label: 'Informal tracking', value: 'minimal' },
      { id: 'pol-025-4', label: 'No finding tracking', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-026',
    text: 'Do you have management review of security/compliance?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.77,
    bestPractice: 'Quarterly management review; KPIs reported; decisions documented',
    practicalExplainer: 'Management review ensures leadership oversight of compliance.',
    standardRefs: 'ISO 27001:9.3, Management Review, Leadership Commitment',
    acceptance: 'Quarterly reviews conducted; documented; actions tracked',
    orderIndex: 22,
    options: [
      { id: 'pol-026-1', label: 'Yes, regular management review', value: 'full' },
      { id: 'pol-026-2', label: 'Annual review', value: 'partial' },
      { id: 'pol-026-3', label: 'Informal updates', value: 'minimal' },
      { id: 'pol-026-4', label: 'No management review', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-027',
    text: 'Do you have continuous compliance monitoring?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.78,
    bestPractice: 'Automated compliance monitoring; real-time alerts; dashboard',
    practicalExplainer: 'Continuous monitoring catches compliance drift early.',
    standardRefs: 'Continuous Monitoring, CSPM, GRC Automation',
    acceptance: 'Automated monitoring active; alerts configured; dashboard available',
    orderIndex: 23,
    options: [
      { id: 'pol-027-1', label: 'Yes, continuous automated monitoring', value: 'full' },
      { id: 'pol-027-2', label: 'Periodic automated checks', value: 'partial' },
      { id: 'pol-027-3', label: 'Manual monitoring', value: 'minimal' },
      { id: 'pol-027-4', label: 'No compliance monitoring', value: 'none' },
    ],
    isRequired: true,
  },
];

// ==========================================
// GOVERNANCE & POLICIES (13)
// ==========================================
export const governanceQuestions: PolicyQuestion[] = [
  {
    id: 'q-pol-028',
    text: 'Do you have an Information Security Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.86,
    bestPractice: 'Comprehensive security policy; management approved; regularly reviewed',
    practicalExplainer: 'Security policy sets the foundation for all security controls.',
    standardRefs: 'ISO 27001:A.5, NIST CSF, Security Policy Framework',
    acceptance: 'Policy documented; management approved; annually reviewed',
    orderIndex: 24,
    options: [
      { id: 'pol-028-1', label: 'Yes, comprehensive security policy', value: 'full' },
      { id: 'pol-028-2', label: 'Basic security policy', value: 'partial' },
      { id: 'pol-028-3', label: 'Informal security guidelines', value: 'minimal' },
      { id: 'pol-028-4', label: 'No security policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-029',
    text: 'Do you have an Acceptable Use Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.75,
    bestPractice: 'Define acceptable use of company systems; employee acknowledgment',
    practicalExplainer: 'AUP sets expectations for how employees use company resources.',
    standardRefs: 'ISO 27001:A.8.1, Acceptable Use Policy, Employee Handbook',
    acceptance: 'AUP documented; employees acknowledged; enforced',
    orderIndex: 25,
    options: [
      { id: 'pol-029-1', label: 'Yes, AUP acknowledged by employees', value: 'full' },
      { id: 'pol-029-2', label: 'Basic AUP exists', value: 'partial' },
      { id: 'pol-029-3', label: 'Informal guidelines', value: 'minimal' },
      { id: 'pol-029-4', label: 'No AUP', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-030',
    text: 'Do you have security awareness training?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'people_change',
    severity: 0.81,
    bestPractice: 'Annual training; phishing simulations; completion tracked',
    practicalExplainer: 'Training helps employees recognize and avoid security threats.',
    standardRefs: 'ISO 27001:A.7.2, NIST CSF PR.AT, Security Awareness',
    acceptance: 'Training conducted annually; completion >95%; phishing tests run',
    orderIndex: 4,
    options: [
      { id: 'pol-030-1', label: 'Yes, comprehensive security training', value: 'full' },
      { id: 'pol-030-2', label: 'Basic annual training', value: 'partial' },
      { id: 'pol-030-3', label: 'Onboarding training only', value: 'minimal' },
      { id: 'pol-030-4', label: 'No security training', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-031',
    text: 'Do you have an Asset Management Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.77,
    bestPractice: 'Inventory all assets; classify; assign owners; lifecycle management',
    practicalExplainer: 'Asset management ensures you know what you need to protect.',
    standardRefs: 'ISO 27001:A.8, NIST CSF ID.AM, Asset Inventory',
    acceptance: 'Asset inventory exists; classified; owners assigned',
    orderIndex: 26,
    options: [
      { id: 'pol-031-1', label: 'Yes, comprehensive asset management', value: 'full' },
      { id: 'pol-031-2', label: 'Basic asset tracking', value: 'partial' },
      { id: 'pol-031-3', label: 'Informal awareness', value: 'minimal' },
      { id: 'pol-031-4', label: 'No asset management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-032',
    text: 'Do you have an Access Control Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.84,
    bestPractice: 'Define access principles; least privilege; need-to-know',
    practicalExplainer: 'Access control policy governs who can access what.',
    standardRefs: 'ISO 27001:A.9, NIST 800-53 AC, Access Control',
    acceptance: 'Policy documented; principles defined; enforced',
    orderIndex: 27,
    options: [
      { id: 'pol-032-1', label: 'Yes, comprehensive access policy', value: 'full' },
      { id: 'pol-032-2', label: 'Basic access guidelines', value: 'partial' },
      { id: 'pol-032-3', label: 'Informal access rules', value: 'minimal' },
      { id: 'pol-032-4', label: 'No access policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-033',
    text: 'Do you have a Business Continuity Plan?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'service_ops',
    severity: 0.83,
    bestPractice: 'Document BCP; identify critical functions; test annually',
    practicalExplainer: 'BCP ensures business operations continue during disruptions.',
    standardRefs: 'ISO 22301, NIST 800-34, Business Continuity',
    acceptance: 'BCP documented; critical functions identified; tested annually',
    orderIndex: 5,
    options: [
      { id: 'pol-033-1', label: 'Yes, tested BCP', value: 'full' },
      { id: 'pol-033-2', label: 'BCP documented, untested', value: 'partial' },
      { id: 'pol-033-3', label: 'Informal continuity plans', value: 'minimal' },
      { id: 'pol-033-4', label: 'No BCP', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-034',
    text: 'Do you have a Vendor Management Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.78,
    bestPractice: 'Due diligence; risk assessment; contract requirements; monitoring',
    practicalExplainer: 'Vendor management ensures third parties meet your standards.',
    standardRefs: 'ISO 27001:A.15, Third-Party Risk, Vendor Assessment',
    acceptance: 'Policy documented; due diligence conducted; contracts reviewed',
    orderIndex: 28,
    options: [
      { id: 'pol-034-1', label: 'Yes, formal vendor management', value: 'full' },
      { id: 'pol-034-2', label: 'Basic vendor vetting', value: 'partial' },
      { id: 'pol-034-3', label: 'Informal vendor awareness', value: 'minimal' },
      { id: 'pol-034-4', label: 'No vendor management', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-035',
    text: 'Do you have an Incident Response Plan?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'service_ops',
    severity: 0.88,
    bestPractice: 'Document IR procedures; define roles; test with tabletop exercises',
    practicalExplainer: 'IR plan ensures coordinated response to security incidents.',
    standardRefs: 'ISO 27001:A.16, NIST 800-61, Incident Response',
    acceptance: 'IR plan documented; roles defined; tested annually',
    orderIndex: 6,
    options: [
      { id: 'pol-035-1', label: 'Yes, tested IR plan', value: 'full' },
      { id: 'pol-035-2', label: 'IR plan documented', value: 'partial' },
      { id: 'pol-035-3', label: 'Informal IR process', value: 'minimal' },
      { id: 'pol-035-4', label: 'No IR plan', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-036',
    text: 'Do you have a Data Classification Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'data_ai',
    severity: 0.8,
    bestPractice: 'Define classification levels; handling requirements; labeling',
    practicalExplainer: 'Data classification ensures appropriate handling by sensitivity.',
    standardRefs: 'ISO 27001:A.8.2, NIST 800-60, Data Classification',
    acceptance: 'Classification scheme defined; handling documented; enforced',
    orderIndex: 5,
    options: [
      { id: 'pol-036-1', label: 'Yes, data classification policy', value: 'full' },
      { id: 'pol-036-2', label: 'Basic classification levels', value: 'partial' },
      { id: 'pol-036-3', label: 'Informal classification', value: 'minimal' },
      { id: 'pol-036-4', label: 'No classification policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-037',
    text: 'Do you have a Cryptographic Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.79,
    bestPractice: 'Define approved algorithms; key management; crypto inventory',
    practicalExplainer: 'Crypto policy ensures consistent, strong encryption.',
    standardRefs: 'ISO 27001:A.10, NIST 800-57, Cryptographic Standards',
    acceptance: 'Approved algorithms defined; key management documented; inventory exists',
    orderIndex: 29,
    options: [
      { id: 'pol-037-1', label: 'Yes, cryptographic policy', value: 'full' },
      { id: 'pol-037-2', label: 'Basic crypto standards', value: 'partial' },
      { id: 'pol-037-3', label: 'Informal guidance', value: 'minimal' },
      { id: 'pol-037-4', label: 'No crypto policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-038',
    text: 'Do you have a Physical Security Policy?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.72,
    bestPractice: 'Define physical controls for facilities, equipment, and media',
    practicalExplainer: 'Physical security protects hardware and prevents unauthorized access.',
    standardRefs: 'ISO 27001:A.11, NIST 800-53 PE, Physical Security',
    acceptance: 'Policy documented; controls implemented; access logged',
    orderIndex: 30,
    options: [
      { id: 'pol-038-1', label: 'Yes, physical security policy', value: 'full' },
      { id: 'pol-038-2', label: 'Basic physical controls', value: 'partial' },
      { id: 'pol-038-3', label: 'Informal security', value: 'minimal' },
      { id: 'pol-038-4', label: 'No physical security policy', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-039',
    text: 'Do you have HR security policies (onboarding/offboarding)?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'people_change',
    severity: 0.8,
    bestPractice: 'Background checks; access provisioning; timely offboarding',
    practicalExplainer:
      'HR security ensures employees have appropriate access throughout lifecycle.',
    standardRefs: 'ISO 27001:A.7, HR Security, Joiner-Mover-Leaver',
    acceptance: 'Onboarding/offboarding documented; background checks; timely access removal',
    orderIndex: 5,
    options: [
      { id: 'pol-039-1', label: 'Yes, comprehensive HR security', value: 'full' },
      { id: 'pol-039-2', label: 'Basic JML process', value: 'partial' },
      { id: 'pol-039-3', label: 'Informal process', value: 'minimal' },
      { id: 'pol-039-4', label: 'No HR security policies', value: 'none' },
    ],
    isRequired: true,
  },
  {
    id: 'q-pol-040',
    text: 'Do you have policy review and update schedule?',
    type: QuestionType.SINGLE_CHOICE,
    persona: Persona.POLICY,
    dimensionKey: 'compliance_policy',
    severity: 0.74,
    bestPractice: 'Annual policy review; version control; change tracking',
    practicalExplainer: 'Regular review keeps policies current and effective.',
    standardRefs: 'ISO 27001:7.5, Document Control, Policy Management',
    acceptance: 'Review schedule exists; versions tracked; changes documented',
    orderIndex: 31,
    options: [
      { id: 'pol-040-1', label: 'Yes, scheduled policy review', value: 'full' },
      { id: 'pol-040-2', label: 'Annual review', value: 'partial' },
      { id: 'pol-040-3', label: 'Ad-hoc updates', value: 'minimal' },
      { id: 'pol-040-4', label: 'No review process', value: 'none' },
    ],
    isRequired: true,
  },
];

// Combined Policy questions
export const policyQuestions: PolicyQuestion[] = [
  ...complianceQuestions,
  ...auditabilityQuestions,
  ...governanceQuestions,
];

export default policyQuestions;
