# Generated by setup script on Sun Jan 25 15:32:38 UTC 2026
project_name = "questionnaire"
environment  = "dev"
location     = "westus2"

tags = {
  Project     = "Adaptive Questionnaire System"
  Environment = "Development"
  ManagedBy   = "Terraform"
}
