# Generated by setup script on Sun Jan 25 15:32:38 UTC 2026
# CRITICAL: Updated to match existing Azure production resources
# - environment: "prod" (was "dev" - would have destroyed 19 resources)
# - location: "australiasoutheast" (was "westus2" - would have recreated ACR)
project_name = "questionnaire"
environment  = "prod"
location     = "australiasoutheast"

tags = {
  Project     = "Adaptive Questionnaire System"
  Environment = "Production"
  ManagedBy   = "Terraform"
}
