# Fix Azure Infrastructure Script
# Run these commands to fix DEV API container and deploy Key Vault
# Generated by AVI-OS Compliance Engine

Write-Host "====================================" -ForegroundColor Cyan
Write-Host " Azure Infrastructure Fix Script" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan

# Prerequisites check
Write-Host "`n[1/6] Checking Azure CLI login..." -ForegroundColor Yellow
$azAccount = az account show 2>$null | ConvertFrom-Json
if (-not $azAccount) {
    Write-Host "ERROR: Not logged into Azure. Run: az login" -ForegroundColor Red
    exit 1
}
Write-Host "Logged in as: $($azAccount.user.name)" -ForegroundColor Green

# ============================================
# TASK 1: Fix DEV API Container App
# ============================================
Write-Host "`n[2/6] Diagnosing DEV API Container App..." -ForegroundColor Yellow

# Check container app status
$devApiStatus = az containerapp show `
    --name ca-questionnaire-api-dev `
    --resource-group rg-questionnaire-dev `
    --query "{status:properties.provisioningState, runningStatus:properties.runningStatus}" `
    --output json 2>$null | ConvertFrom-Json

if ($devApiStatus) {
    Write-Host "Current Status: $($devApiStatus.status)" -ForegroundColor Cyan
} else {
    Write-Host "Container app not found or inaccessible" -ForegroundColor Red
}

# Get container logs to diagnose issue
Write-Host "`n[3/6] Fetching container logs..." -ForegroundColor Yellow
az containerapp logs show `
    --name ca-questionnaire-api-dev `
    --resource-group rg-questionnaire-dev `
    --tail 50 `
    --type console 2>$null

# Attempt restart/redeploy
Write-Host "`n[4/6] Restarting DEV API container..." -ForegroundColor Yellow
az containerapp revision restart `
    --name ca-questionnaire-api-dev `
    --resource-group rg-questionnaire-dev `
    --revision (az containerapp revision list `
        --name ca-questionnaire-api-dev `
        --resource-group rg-questionnaire-dev `
        --query "[0].name" --output tsv 2>$null) 2>$null

if ($LASTEXITCODE -ne 0) {
    Write-Host "Restart failed. Attempting full redeploy..." -ForegroundColor Yellow
    
    # Get latest image from ACR
    $latestImage = az acr repository show-tags `
        --name acrquestionnairedev `
        --repository quiz-api `
        --orderby time_desc `
        --top 1 `
        --output tsv 2>$null
    
    if ($latestImage) {
        az containerapp update `
            --name ca-questionnaire-api-dev `
            --resource-group rg-questionnaire-dev `
            --image "acrquestionnairedev.azurecr.io/quiz-api:$latestImage"
    } else {
        Write-Host "No image found in dev registry. Push image first." -ForegroundColor Red
    }
}

# ============================================
# TASK 2: Deploy Key Vault to Production
# ============================================
Write-Host "`n[5/6] Checking Key Vault in Production..." -ForegroundColor Yellow

$kvExists = az keyvault list `
    --resource-group rg-questionnaire-prod `
    --query "[?starts_with(name, 'kv-quest-prod')]" `
    --output json 2>$null | ConvertFrom-Json

if ($kvExists -and $kvExists.Count -gt 0) {
    Write-Host "Key Vault already exists: $($kvExists[0].name)" -ForegroundColor Green
} else {
    Write-Host "Key Vault not found in production. Deploying via Terraform..." -ForegroundColor Yellow
    
    # Navigate to terraform directory and apply
    Push-Location c:\Repos\Quiz-to-Build\infrastructure\terraform
    
    Write-Host "Running Terraform plan for Key Vault..." -ForegroundColor Yellow
    terraform plan -target=module.keyvault -out=keyvault.tfplan
    
    Write-Host "`nReview the plan above. To apply, run:" -ForegroundColor Cyan
    Write-Host "  terraform apply keyvault.tfplan" -ForegroundColor White
    
    Pop-Location
}

# ============================================
# TASK 3: Upgrade DEV PostgreSQL to v16
# ============================================
Write-Host "`n[6/6] Checking PostgreSQL version parity..." -ForegroundColor Yellow

$devPg = az postgres flexible-server show `
    --name psql-questionnaire-dev `
    --resource-group rg-questionnaire-dev `
    --query "{version:version, state:state}" `
    --output json 2>$null | ConvertFrom-Json

$prodPg = az postgres flexible-server show `
    --name psql-questionnaire-prod `
    --resource-group rg-questionnaire-prod `
    --query "{version:version, state:state}" `
    --output json 2>$null | ConvertFrom-Json

if ($devPg -and $prodPg) {
    Write-Host "DEV PostgreSQL:  v$($devPg.version) ($($devPg.state))" -ForegroundColor Cyan
    Write-Host "PROD PostgreSQL: v$($prodPg.version) ($($prodPg.state))" -ForegroundColor Cyan
    
    if ($devPg.version -ne $prodPg.version) {
        Write-Host "`nVersion mismatch detected. To upgrade DEV to v16, run:" -ForegroundColor Yellow
        Write-Host @"

  az postgres flexible-server update \
    --name psql-questionnaire-dev \
    --resource-group rg-questionnaire-dev \
    --version 16

"@ -ForegroundColor White
        Write-Host "WARNING: This requires a restart and may take 10-30 minutes." -ForegroundColor Red
    } else {
        Write-Host "Versions match - no action needed." -ForegroundColor Green
    }
}

Write-Host "`n====================================" -ForegroundColor Cyan
Write-Host " Infrastructure Fix Complete" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host "`nNext steps:" -ForegroundColor Yellow
Write-Host "1. Review any errors above" -ForegroundColor White
Write-Host "2. Apply Terraform plan if Key Vault needed" -ForegroundColor White
Write-Host "3. Upgrade DEV PostgreSQL if version mismatch" -ForegroundColor White
Write-Host "4. Verify DEV API container health" -ForegroundColor White
