#!/bin/bash
# =============================================================================
# Azure Deployment Setup Script
# Creates the Terraform state storage and prepares the environment
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=============================================${NC}"
echo -e "${GREEN}  Azure Deployment Setup                      ${NC}"
echo -e "${GREEN}  Adaptive Questionnaire System               ${NC}"
echo -e "${GREEN}=============================================${NC}"

# Configuration
LOCATION="${AZURE_LOCATION:-eastus}"
STATE_RESOURCE_GROUP="rg-terraform-state"
STATE_STORAGE_ACCOUNT="stquestterraform$(openssl rand -hex 4)"
STATE_CONTAINER="tfstate"

# Check prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed. Please install it first.${NC}"
    echo "Visit: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: Terraform is not installed. Please install it first.${NC}"
    echo "Visit: https://learn.hashicorp.com/tutorials/terraform/install-cli"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed. Please install it first.${NC}"
    exit 1
fi

echo -e "${GREEN}All prerequisites are installed.${NC}"

# Check Azure login
echo -e "\n${YELLOW}Checking Azure login status...${NC}"
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Initiating login...${NC}"
    az login
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
echo -e "${GREEN}Logged in to subscription: ${SUBSCRIPTION_NAME}${NC}"

# Create resource group for Terraform state
echo -e "\n${YELLOW}Creating Terraform state resource group...${NC}"
az group create \
    --name "$STATE_RESOURCE_GROUP" \
    --location "$LOCATION" \
    --tags "Purpose=TerraformState" "Project=Questionnaire" \
    --output none

echo -e "${GREEN}Resource group created: ${STATE_RESOURCE_GROUP}${NC}"

# Create storage account for Terraform state
echo -e "\n${YELLOW}Creating Terraform state storage account...${NC}"
az storage account create \
    --name "$STATE_STORAGE_ACCOUNT" \
    --resource-group "$STATE_RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --https-only true \
    --min-tls-version TLS1_2 \
    --allow-blob-public-access false \
    --output none

echo -e "${GREEN}Storage account created: ${STATE_STORAGE_ACCOUNT}${NC}"

# Create blob container for Terraform state
echo -e "\n${YELLOW}Creating Terraform state container...${NC}"
az storage container create \
    --name "$STATE_CONTAINER" \
    --account-name "$STATE_STORAGE_ACCOUNT" \
    --auth-mode login \
    --output none

echo -e "${GREEN}Container created: ${STATE_CONTAINER}${NC}"

# Update backend.tf with actual values
echo -e "\n${YELLOW}Updating Terraform backend configuration...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../infrastructure/terraform"

cat > "$TERRAFORM_DIR/backend.tf" << EOF
terraform {
  backend "azurerm" {
    resource_group_name  = "${STATE_RESOURCE_GROUP}"
    storage_account_name = "${STATE_STORAGE_ACCOUNT}"
    container_name       = "${STATE_CONTAINER}"
    key                  = "questionnaire.dev.tfstate"
  }
}
EOF

echo -e "${GREEN}Backend configuration updated.${NC}"

# Create terraform.tfvars
echo -e "\n${YELLOW}Creating terraform.tfvars...${NC}"
cat > "$TERRAFORM_DIR/terraform.tfvars" << EOF
# Generated by setup script on $(date)
project_name = "questionnaire"
environment  = "dev"
location     = "${LOCATION}"

tags = {
  Project     = "Adaptive Questionnaire System"
  Environment = "Development"
  ManagedBy   = "Terraform"
}
EOF

echo -e "${GREEN}terraform.tfvars created.${NC}"

# Output summary
echo -e "\n${GREEN}=============================================${NC}"
echo -e "${GREEN}  Setup Complete!                             ${NC}"
echo -e "${GREEN}=============================================${NC}"
echo -e "\nConfiguration:"
echo -e "  Subscription:        ${SUBSCRIPTION_NAME}"
echo -e "  Location:            ${LOCATION}"
echo -e "  State Resource Group: ${STATE_RESOURCE_GROUP}"
echo -e "  State Storage Account: ${STATE_STORAGE_ACCOUNT}"
echo -e "\nNext steps:"
echo -e "  1. Run: ${YELLOW}./scripts/deploy.sh${NC}"
echo -e "  2. Wait for infrastructure to be provisioned (~10-15 minutes)"
echo -e "  3. Access your API at the URL shown in the output"
#!/bin/bash
# =============================================================================
# Azure Deployment Setup Script
# Creates the Terraform state storage and prepares the environment
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}=============================================${NC}"
echo -e "${GREEN}  Azure Deployment Setup                      ${NC}"
echo -e "${GREEN}  Adaptive Questionnaire System               ${NC}"
echo -e "${GREEN}=============================================${NC}"

# Configuration
LOCATION="${AZURE_LOCATION:-eastus}"
STATE_RESOURCE_GROUP="rg-terraform-state"
STATE_STORAGE_ACCOUNT="stquestterraform$(openssl rand -hex 4)"
STATE_CONTAINER="tfstate"

# Check prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed. Please install it first.${NC}"
    echo "Visit: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: Terraform is not installed. Please install it first.${NC}"
    echo "Visit: https://learn.hashicorp.com/tutorials/terraform/install-cli"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed. Please install it first.${NC}"
    exit 1
fi

echo -e "${GREEN}All prerequisites are installed.${NC}"

# Check Azure login
echo -e "\n${YELLOW}Checking Azure login status...${NC}"
if ! az account show &> /dev/null; then
    echo -e "${YELLOW}Not logged in to Azure. Initiating login...${NC}"
    az login
fi

SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)
echo -e "${GREEN}Logged in to subscription: ${SUBSCRIPTION_NAME}${NC}"

# Create resource group for Terraform state
echo -e "\n${YELLOW}Creating Terraform state resource group...${NC}"
az group create \
    --name "$STATE_RESOURCE_GROUP" \
    --location "$LOCATION" \
    --tags "Purpose=TerraformState" "Project=Questionnaire" \
    --output none

echo -e "${GREEN}Resource group created: ${STATE_RESOURCE_GROUP}${NC}"

# Create storage account for Terraform state
echo -e "\n${YELLOW}Creating Terraform state storage account...${NC}"
az storage account create \
    --name "$STATE_STORAGE_ACCOUNT" \
    --resource-group "$STATE_RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --https-only true \
    --min-tls-version TLS1_2 \
    --allow-blob-public-access false \
    --output none

echo -e "${GREEN}Storage account created: ${STATE_STORAGE_ACCOUNT}${NC}"

# Create blob container for Terraform state
echo -e "\n${YELLOW}Creating Terraform state container...${NC}"
az storage container create \
    --name "$STATE_CONTAINER" \
    --account-name "$STATE_STORAGE_ACCOUNT" \
    --auth-mode login \
    --output none

echo -e "${GREEN}Container created: ${STATE_CONTAINER}${NC}"

# Update backend.tf with actual values
echo -e "\n${YELLOW}Updating Terraform backend configuration...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$SCRIPT_DIR/../infrastructure/terraform"

cat > "$TERRAFORM_DIR/backend.tf" << EOF
terraform {
  backend "azurerm" {
    resource_group_name  = "${STATE_RESOURCE_GROUP}"
    storage_account_name = "${STATE_STORAGE_ACCOUNT}"
    container_name       = "${STATE_CONTAINER}"
    key                  = "questionnaire.dev.tfstate"
  }
}
EOF

echo -e "${GREEN}Backend configuration updated.${NC}"

# Create terraform.tfvars
echo -e "\n${YELLOW}Creating terraform.tfvars...${NC}"
cat > "$TERRAFORM_DIR/terraform.tfvars" << EOF
# Generated by setup script on $(date)
project_name = "questionnaire"
environment  = "dev"
location     = "${LOCATION}"

tags = {
  Project     = "Adaptive Questionnaire System"
  Environment = "Development"
  ManagedBy   = "Terraform"
}
EOF

echo -e "${GREEN}terraform.tfvars created.${NC}"

# Output summary
echo -e "\n${GREEN}=============================================${NC}"
echo -e "${GREEN}  Setup Complete!                             ${NC}"
echo -e "${GREEN}=============================================${NC}"
echo -e "\nConfiguration:"
echo -e "  Subscription:        ${SUBSCRIPTION_NAME}"
echo -e "  Location:            ${LOCATION}"
echo -e "  State Resource Group: ${STATE_RESOURCE_GROUP}"
echo -e "  State Storage Account: ${STATE_STORAGE_ACCOUNT}"
echo -e "\nNext steps:"
echo -e "  1. Run: ${YELLOW}./scripts/deploy.sh${NC}"
echo -e "  2. Wait for infrastructure to be provisioned (~10-15 minutes)"
echo -e "  3. Access your API at the URL shown in the output"
