/**
 * Markdown Renderer Service Unit Tests
 */
import {
  MarkdownRendererService,
  MarkdownDocument,
  DocumentSection,
  TableData,
} from './markdown-renderer.service';

describe('MarkdownRendererService', () => {
  let service: MarkdownRendererService;

  beforeEach(() => {
    service = new MarkdownRendererService();
  });

  it('should be defined', () => {
    expect(service).toBeDefined();
  });

  describe('renderDocument', () => {
    it('should render a minimal document with title only', () => {
      const doc: MarkdownDocument = { title: 'Test Doc', sections: [] };
      const result = service.renderDocument(doc);

      expect(result).toContain('# Test Doc');
    });

    it('should render subtitle in italics', () => {
      const doc: MarkdownDocument = {
        title: 'Test',
        subtitle: 'A subtitle',
        sections: [],
      };
      const result = service.renderDocument(doc);

      expect(result).toContain('*A subtitle*');
    });

    it('should render metadata between horizontal rules', () => {
      const doc: MarkdownDocument = {
        title: 'Test',
        metadata: { Author: 'John', Date: '2024-01-01' },
        sections: [],
      };
      const result = service.renderDocument(doc);

      expect(result).toContain('**Author:** John');
      expect(result).toContain('**Date:** 2024-01-01');
      expect(result).toContain('---');
    });

    it('should skip metadata when empty', () => {
      const doc: MarkdownDocument = {
        title: 'Test',
        metadata: {},
        sections: [],
      };
      const result = service.renderDocument(doc);

      // Should not contain metadata separator other than possible TOC
      const metaCount = (result.match(/\*\*.*:\*\*/g) || []).length;
      expect(metaCount).toBe(0);
    });

    it('should render table of contents for sections', () => {
      const doc: MarkdownDocument = {
        title: 'Test',
        sections: [
          { title: 'Introduction', content: 'Intro text', level: 2 },
          { title: 'Conclusion', content: 'Conclusion text', level: 2 },
        ],
      };
      const result = service.renderDocument(doc);

      expect(result).toContain('## Table of Contents');
      expect(result).toContain('[Introduction]');
      expect(result).toContain('[Conclusion]');
    });

    it('should render footer in italics', () => {
      const doc: MarkdownDocument = {
        title: 'Test',
        sections: [],
        footer: 'Generated by Q2B',
      };
      const result = service.renderDocument(doc);

      expect(result).toContain('*Generated by Q2B*');
    });

    it('should render full document with all parts', () => {
      const doc: MarkdownDocument = {
        title: 'Business Plan',
        subtitle: 'TechCorp Inc.',
        metadata: { Version: '1.0' },
        sections: [{ title: 'Executive Summary', content: 'This is the summary.', level: 2 }],
        footer: 'Confidential',
      };
      const result = service.renderDocument(doc);

      expect(result).toContain('# Business Plan');
      expect(result).toContain('*TechCorp Inc.*');
      expect(result).toContain('**Version:** 1.0');
      expect(result).toContain('## Executive Summary');
      expect(result).toContain('This is the summary.');
      expect(result).toContain('*Confidential*');
    });
  });

  describe('renderSection', () => {
    it('should render section with correct heading level', () => {
      const section: DocumentSection = { title: 'Heading', content: 'Text', level: 2 };
      const result = service.renderSection(section);

      expect(result).toContain('## Heading');
      expect(result).toContain('Text');
    });

    it('should render level 3 heading', () => {
      const section: DocumentSection = { title: 'Sub', content: 'Content', level: 3 };
      const result = service.renderSection(section);

      expect(result).toContain('### Sub');
    });

    it('should recursively render subsections', () => {
      const section: DocumentSection = {
        title: 'Parent',
        content: 'Parent content',
        level: 2,
        subsections: [{ title: 'Child', content: 'Child content', level: 3 }],
      };
      const result = service.renderSection(section);

      expect(result).toContain('## Parent');
      expect(result).toContain('### Child');
      expect(result).toContain('Child content');
    });
  });

  describe('generateToc', () => {
    it('should generate links for sections', () => {
      const sections: DocumentSection[] = [
        { title: 'Executive Summary', content: '', level: 2 },
        { title: 'Market Analysis', content: '', level: 2 },
      ];
      const result = service.generateToc(sections);

      expect(result).toContain('- [Executive Summary](#executive-summary)');
      expect(result).toContain('- [Market Analysis](#market-analysis)');
    });

    it('should indent subsections', () => {
      const sections: DocumentSection[] = [
        {
          title: 'Parent',
          content: '',
          level: 2,
          subsections: [{ title: 'Child', content: '', level: 3 }],
        },
      ];
      const result = service.generateToc(sections);

      expect(result).toContain('- [Parent](#parent)');
      expect(result).toContain('  - [Child](#child)');
    });

    it('should return empty string for empty sections', () => {
      const result = service.generateToc([]);
      expect(result).toBe('');
    });
  });

  describe('renderTable', () => {
    it('should render table with headers and rows', () => {
      const data: TableData = {
        headers: ['Name', 'Value'],
        rows: [
          ['Revenue', '$1M'],
          ['Costs', '$500K'],
        ],
      };
      const result = service.renderTable(data);

      expect(result).toContain('| Name | Value |');
      expect(result).toContain('| --- | --- |');
      expect(result).toContain('| Revenue | $1M |');
      expect(result).toContain('| Costs | $500K |');
    });

    it('should render caption when provided', () => {
      const data: TableData = {
        headers: ['A'],
        rows: [['1']],
        caption: 'Table 1',
      };
      const result = service.renderTable(data);

      expect(result).toContain('**Table 1**');
    });

    it('should render table without caption', () => {
      const data: TableData = {
        headers: ['A'],
        rows: [['1']],
      };
      const result = service.renderTable(data);

      expect(result).not.toContain('**');
    });
  });

  describe('renderList', () => {
    it('should render unordered list by default', () => {
      const result = service.renderList(['Apple', 'Banana', 'Cherry']);

      expect(result).toContain('- Apple');
      expect(result).toContain('- Banana');
      expect(result).toContain('- Cherry');
    });

    it('should render ordered list when ordered is true', () => {
      const result = service.renderList(['First', 'Second', 'Third'], true);

      expect(result).toContain('1. First');
      expect(result).toContain('2. Second');
      expect(result).toContain('3. Third');
    });
  });

  describe('renderCodeBlock', () => {
    it('should render code block with language', () => {
      const result = service.renderCodeBlock('const x = 1;', 'typescript');

      expect(result).toContain('```typescript');
      expect(result).toContain('const x = 1;');
      expect(result).toContain('```');
    });

    it('should render code block without language', () => {
      const result = service.renderCodeBlock('echo hello');

      expect(result).toContain('```\n');
      expect(result).toContain('echo hello');
    });
  });

  describe('renderBlockquote', () => {
    it('should prefix each line with >', () => {
      const result = service.renderBlockquote('Line 1\nLine 2');

      expect(result).toContain('> Line 1');
      expect(result).toContain('> Line 2');
    });

    it('should handle single line', () => {
      const result = service.renderBlockquote('A single quote');

      expect(result).toBe('> A single quote\n');
    });
  });

  describe('renderCallout', () => {
    it('should render info callout with icon', () => {
      const result = service.renderCallout('info', 'Some information');

      expect(result).toContain('ℹ️');
      expect(result).toContain('**Info**');
      expect(result).toContain('Some information');
    });

    it('should render warning callout', () => {
      const result = service.renderCallout('warning', 'Be careful');

      expect(result).toContain('⚠️');
      expect(result).toContain('**Warning**');
    });

    it('should render success callout', () => {
      const result = service.renderCallout('success', 'All good');

      expect(result).toContain('✅');
      expect(result).toContain('**Success**');
    });

    it('should render error callout', () => {
      const result = service.renderCallout('error', 'Something broke');

      expect(result).toContain('❌');
      expect(result).toContain('**Error**');
    });
  });

  describe('formatContent', () => {
    it('should collapse excessive newlines', () => {
      const result = service.formatContent('Hello\n\n\n\n\nWorld');

      expect(result).not.toContain('\n\n\n');
    });

    it('should convert bullet symbols to markdown dashes', () => {
      const result = service.formatContent('• Item 1\n● Item 2');

      expect(result).toContain('- Item 1');
      expect(result).toContain('- Item 2');
    });

    it('should fix excessive asterisks', () => {
      const result = service.formatContent('***bold***');

      expect(result).toContain('**bold**');
    });

    it('should ensure proper header spacing', () => {
      const result = service.formatContent('## Header');

      expect(result).toContain('## Header');
    });

    it('should trim whitespace', () => {
      const result = service.formatContent('  hello  \n');

      expect(result.trim()).toBe('hello');
    });
  });

  describe('parseAiOutput', () => {
    it('should parse headers and content into sections', () => {
      const raw = '## Introduction\nThis is intro.\n## Conclusion\nFinal thoughts.';
      const sections = service.parseAiOutput(raw);

      expect(sections).toHaveLength(2);
      expect(sections[0].title).toBe('Introduction');
      expect(sections[0].content).toBe('This is intro.');
      expect(sections[0].level).toBe(2);
      expect(sections[1].title).toBe('Conclusion');
      expect(sections[1].content).toBe('Final thoughts.');
    });

    it('should handle different heading levels', () => {
      const raw = '# H1\nContent 1\n### H3\nContent 3\n#### H4\nContent 4';
      const sections = service.parseAiOutput(raw);

      expect(sections).toHaveLength(3);
      expect(sections[0].level).toBe(1);
      expect(sections[1].level).toBe(3);
      expect(sections[2].level).toBe(4);
    });

    it('should handle content before first header (ignored)', () => {
      const raw = 'Preamble text\n## Section\nContent';
      const sections = service.parseAiOutput(raw);

      expect(sections).toHaveLength(1);
      expect(sections[0].title).toBe('Section');
    });

    it('should return empty array for no headers', () => {
      const sections = service.parseAiOutput('Just plain text without headers');

      expect(sections).toEqual([]);
    });

    it('should handle empty content between headers', () => {
      const raw = '## A\n## B\nContent B';
      const sections = service.parseAiOutput(raw);

      expect(sections).toHaveLength(2);
      expect(sections[0].content).toBe('');
      expect(sections[1].content).toBe('Content B');
    });
  });

  describe('toHtml', () => {
    it('should convert h1 headers', () => {
      const result = service.toHtml('# Title');
      expect(result).toContain('<h1>Title</h1>');
    });

    it('should convert h2 through h4 headers', () => {
      const result = service.toHtml('## H2\n### H3\n#### H4');
      expect(result).toContain('<h2>H2</h2>');
      expect(result).toContain('<h3>H3</h3>');
      expect(result).toContain('<h4>H4</h4>');
    });

    it('should convert bold text', () => {
      const result = service.toHtml('**bold text**');
      expect(result).toContain('<strong>bold text</strong>');
    });

    it('should convert italic text', () => {
      const result = service.toHtml('*italic text*');
      expect(result).toContain('<em>italic text</em>');
    });

    it('should convert list items', () => {
      const result = service.toHtml('- Item 1\n- Item 2');
      expect(result).toContain('<li>Item 1</li>');
      expect(result).toContain('<li>Item 2</li>');
      expect(result).toContain('<ul>');
    });

    it('should wrap regular lines in paragraphs', () => {
      const result = service.toHtml('A regular paragraph');
      expect(result).toContain('<p>A regular paragraph</p>');
    });
  });
});
