name: Deploy

on:
  push:
    branches:
      - main

jobs:
  verify-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check health
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null http://example.com/health)
          if [ $response -eq 200 ]; then
            echo 'Deployment successful - Health check passed'
          else
            echo 'Deployment failed - health check did not return 200 after retries'
            exit 1
          fi